<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 How Many Experimental Units are Required to Compare Two Treatments? | Design of Experiments and Observational Studies</title>
  <meta name="description" content="An Introduction to Design, Causal Inference,and Analysis Using R" />
  <meta name="generator" content="bookdown 0.12 and GitBook 2.6.7" />

  <meta property="og:title" content="5 How Many Experimental Units are Required to Compare Two Treatments? | Design of Experiments and Observational Studies" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="An Introduction to Design, Causal Inference,and Analysis Using R" />
  <meta name="github-repo" content="scidesign/designbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 How Many Experimental Units are Required to Compare Two Treatments? | Design of Experiments and Observational Studies" />
  
  <meta name="twitter:description" content="An Introduction to Design, Causal Inference,and Analysis Using R" />
  

<meta name="author" content="Nathan Taback" />


<meta name="date" content="2019-10-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="completely-randomized-designs-comparing-two-treatments.html">
<link rel="next" href="causal-inference.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-123360659-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-123360659-2');
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a></li>
<li class="chapter" data-level="2" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>2</b> Introduction</a><ul>
<li class="chapter" data-level="2.1" data-path="introduction.html"><a href="introduction.html#why-design-scientific-studies"><i class="fa fa-check"></i><b>2.1</b> Why Design Scientific Studies?</a></li>
<li class="chapter" data-level="2.2" data-path="introduction.html"><a href="introduction.html#big-data-and-designing-scientific-studies"><i class="fa fa-check"></i><b>2.2</b> Big Data and Designing Scientific Studies</a><ul>
<li class="chapter" data-level="2.2.1" data-path="introduction.html"><a href="introduction.html#what-is-big-data-and-why-does-it-matter"><i class="fa fa-check"></i><b>2.2.1</b> What is Big data and why does it matter?</a></li>
<li class="chapter" data-level="2.2.2" data-path="introduction.html"><a href="introduction.html#is-statistical-sampling-and-randomization-still-relevant-in-the-era-of-big-data"><i class="fa fa-check"></i><b>2.2.2</b> Is statistical sampling and randomization still relevant in the era of Big Data?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html"><i class="fa fa-check"></i><b>3</b> Review of Mathematical Statistics</a><ul>
<li class="chapter" data-level="3.1" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#data"><i class="fa fa-check"></i><b>3.1</b> Data</a></li>
<li class="chapter" data-level="3.2" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#distributions"><i class="fa fa-check"></i><b>3.2</b> Distributions</a><ul>
<li class="chapter" data-level="3.2.1" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#continuous-distributions"><i class="fa fa-check"></i><b>3.2.1</b> Continuous Distributions</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#randomness"><i class="fa fa-check"></i><b>3.3</b> Randomness</a></li>
<li class="chapter" data-level="3.4" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#parameters-and-statistics"><i class="fa fa-check"></i><b>3.4</b> Parameters and Statistics</a></li>
<li class="chapter" data-level="3.5" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#residuals-and-degress-of-freedom"><i class="fa fa-check"></i><b>3.5</b> Residuals and Degress of Freedom</a></li>
<li class="chapter" data-level="3.6" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#the-normal-distribution"><i class="fa fa-check"></i><b>3.6</b> The Normal Distribution</a><ul>
<li class="chapter" data-level="3.6.1" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#exercises"><i class="fa fa-check"></i><b>3.6.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#quantile-quantile-plots"><i class="fa fa-check"></i><b>3.7</b> Quantile-Quantile Plots</a><ul>
<li class="chapter" data-level="3.7.1" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#normal-quantile-plots"><i class="fa fa-check"></i><b>3.7.1</b> Normal Quantile Plots</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#central-limit-theorem"><i class="fa fa-check"></i><b>3.8</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="3.9" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#chi-square-distribution"><i class="fa fa-check"></i><b>3.9</b> Chi-Square Distribution</a></li>
<li class="chapter" data-level="3.10" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#t-distribution"><i class="fa fa-check"></i><b>3.10</b> t Distribution</a><ul>
<li class="chapter" data-level="3.10.1" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#exercises-1"><i class="fa fa-check"></i><b>3.10.1</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#f-distribution"><i class="fa fa-check"></i><b>3.11</b> F Distribution</a></li>
<li class="chapter" data-level="3.12" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#significance-testing-and-basic-decision-theory-in-hypothesis-testing"><i class="fa fa-check"></i><b>3.12</b> Significance Testing and Basic Decision Theory in Hypothesis Testing</a></li>
<li class="chapter" data-level="3.13" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#linear-regression"><i class="fa fa-check"></i><b>3.13</b> Linear Regression</a><ul>
<li class="chapter" data-level="3.13.1" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#covariates-in-regression"><i class="fa fa-check"></i><b>3.13.1</b> Covariates in Regression</a></li>
<li class="chapter" data-level="3.13.2" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#weighing-problem"><i class="fa fa-check"></i><b>3.13.2</b> Weighing Problem</a></li>
</ul></li>
<li class="chapter" data-level="3.14" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#questions"><i class="fa fa-check"></i><b>3.14</b> Questions</a></li>
<li class="chapter" data-level="3.15" data-path="review-of-mathematical-statistics.html"><a href="review-of-mathematical-statistics.html#solutions-to-questions"><i class="fa fa-check"></i><b>3.15</b> Solutions to Questions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html"><i class="fa fa-check"></i><b>4</b> Completely Randomized Designs: Comparing Two Treatments</a><ul>
<li class="chapter" data-level="4.1" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#comparing-two-treatments"><i class="fa fa-check"></i><b>4.1</b> Comparing Two Treatments</a></li>
<li class="chapter" data-level="4.2" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#treatment-assignment-mechanism-and-propensity-score"><i class="fa fa-check"></i><b>4.2</b> Treatment Assignment Mechanism and Propensity Score</a><ul>
<li class="chapter" data-level="4.2.1" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#propensity-score"><i class="fa fa-check"></i><b>4.2.1</b> Propensity Score</a></li>
<li class="chapter" data-level="4.2.2" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#assignment-mechanism"><i class="fa fa-check"></i><b>4.2.2</b> Assignment Mechanism</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#completely-randomized-experiment"><i class="fa fa-check"></i><b>4.3</b> Completely Randomized Experiment</a><ul>
<li class="chapter" data-level="4.3.1" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#example"><i class="fa fa-check"></i><b>4.3.1</b> Example</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#the-randomization-distribution"><i class="fa fa-check"></i><b>4.4</b> The Randomization Distribution</a></li>
<li class="chapter" data-level="4.5" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#the-randomization-p-value"><i class="fa fa-check"></i><b>4.5</b> The Randomization p-value</a></li>
<li class="chapter" data-level="4.6" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#two-sided-randomization-p-value"><i class="fa fa-check"></i><b>4.6</b> Two-Sided Randomization P value</a></li>
<li class="chapter" data-level="4.7" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#other-test-statistics"><i class="fa fa-check"></i><b>4.7</b> Other Test Statistics</a></li>
<li class="chapter" data-level="4.8" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#calculating-the-randomization-p-value-using-monte-carlo-sampling"><i class="fa fa-check"></i><b>4.8</b> Calculating the Randomization P-value using Monte Carlo Sampling</a><ul>
<li class="chapter" data-level="4.8.1" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#does-caffeine-have-an-effect-on-reaction-time"><i class="fa fa-check"></i><b>4.8.1</b> Does Caffeine Have an Effect on Reaction Time?</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#properties-of-the-randomization-test"><i class="fa fa-check"></i><b>4.9</b> Properties of the Randomization Test</a></li>
<li class="chapter" data-level="4.10" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#the-two-sample-t-test"><i class="fa fa-check"></i><b>4.10</b> The two-sample t-test</a></li>
<li class="chapter" data-level="4.11" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#randomized-paired-comparison"><i class="fa fa-check"></i><b>4.11</b> Randomized paired comparison</a></li>
<li class="chapter" data-level="4.12" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#the-randomization-test-for-a-randomized-paired-design"><i class="fa fa-check"></i><b>4.12</b> The Randomization Test for a Randomized Paired Design</a></li>
<li class="chapter" data-level="4.13" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#paired-t-test"><i class="fa fa-check"></i><b>4.13</b> Paired t-test</a></li>
<li class="chapter" data-level="4.14" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#questions-1"><i class="fa fa-check"></i><b>4.14</b> Questions</a></li>
<li class="chapter" data-level="4.15" data-path="completely-randomized-designs-comparing-two-treatments.html"><a href="completely-randomized-designs-comparing-two-treatments.html#solutions-to-questions-1"><i class="fa fa-check"></i><b>4.15</b> Solutions to Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html"><i class="fa fa-check"></i><b>5</b> How Many Experimental Units are Required to Compare Two Treatments?</a><ul>
<li class="chapter" data-level="5.1" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#clinical-trials"><i class="fa fa-check"></i><b>5.1</b> Clinical Trials</a><ul>
<li class="chapter" data-level="5.1.1" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#phases-of-clinical-trials"><i class="fa fa-check"></i><b>5.1.1</b> Phases of clinical trials</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#statistical-hypotheses-and-the-number-of-experimental-units"><i class="fa fa-check"></i><b>5.2</b> Statistical Hypotheses and the Number of Experimental Units</a></li>
<li class="chapter" data-level="5.3" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#power-of-the-one-sample-z-test"><i class="fa fa-check"></i><b>5.3</b> Power of the One Sample z-test</a><ul>
<li class="chapter" data-level="5.3.1" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#exercises-2"><i class="fa fa-check"></i><b>5.3.1</b> Exercises</a></li>
<li class="chapter" data-level="5.3.2" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#calculating-the-power-of-the-one-sample-z-test-using-r"><i class="fa fa-check"></i><b>5.3.2</b> Calculating the Power of the One Sample z-test using R</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#power-of-the-one-sample-t-test"><i class="fa fa-check"></i><b>5.4</b> Power of the one-sample t-test</a><ul>
<li class="chapter" data-level="5.4.1" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#calculating-the-power-of-the-one-sample-t-test-using-r"><i class="fa fa-check"></i><b>5.4.1</b> Calculating the Power of the One Sample t-test using R</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#power-of-two-sample-t-test"><i class="fa fa-check"></i><b>5.5</b> Power of two sample t test</a><ul>
<li class="chapter" data-level="5.5.1" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#calculating-the-power-of-the-two-sample-t-test-using-r"><i class="fa fa-check"></i><b>5.5.1</b> Calculating the Power of the Two Sample t-test using R</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#effect-size"><i class="fa fa-check"></i><b>5.6</b> Effect size</a></li>
<li class="chapter" data-level="5.7" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#sample-size---known-variance-and-equal-allocation"><i class="fa fa-check"></i><b>5.7</b> Sample size - known variance and equal allocation</a></li>
<li class="chapter" data-level="5.8" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#sample-size---known-variance-and-unequal-allocation"><i class="fa fa-check"></i><b>5.8</b> Sample size - known variance and unequal allocation</a></li>
<li class="chapter" data-level="5.9" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#comparing-proportions-for-binary-outcomes"><i class="fa fa-check"></i><b>5.9</b> Comparing Proportions for Binary Outcomes</a></li>
<li class="chapter" data-level="5.10" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#calculating-power-by-simulation"><i class="fa fa-check"></i><b>5.10</b> Calculating Power by simulation</a></li>
<li class="chapter" data-level="5.11" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#questions-2"><i class="fa fa-check"></i><b>5.11</b> Questions</a></li>
<li class="chapter" data-level="5.12" data-path="how-many-experimental-units-are-required-to-compare-two-treatments.html"><a href="how-many-experimental-units-are-required-to-compare-two-treatments.html#solutions-to-questions-2"><i class="fa fa-check"></i><b>5.12</b> Solutions to Questions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="causal-inference.html"><a href="causal-inference.html"><i class="fa fa-check"></i><b>6</b> Causal Inference</a><ul>
<li class="chapter" data-level="6.1" data-path="causal-inference.html"><a href="causal-inference.html#the-fundemental-problem-of-causal-inference"><i class="fa fa-check"></i><b>6.1</b> The Fundemental Problem of Causal Inference</a><ul>
<li class="chapter" data-level="6.1.1" data-path="causal-inference.html"><a href="causal-inference.html#example-of-the-fundemental-problem"><i class="fa fa-check"></i><b>6.1.1</b> Example of the fundemental problem</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="causal-inference.html"><a href="causal-inference.html#randomized-experiments-as-a-solution-to-the-fundemental-problem-of-causal-inference"><i class="fa fa-check"></i><b>6.2</b> Randomized experiments as a solution to the fundemental problem of causal inference</a></li>
<li class="chapter" data-level="6.3" data-path="causal-inference.html"><a href="causal-inference.html#average-causal-effects-and-randomized-experiments"><i class="fa fa-check"></i><b>6.3</b> Average causal effects and randomized experiments</a><ul>
<li class="chapter" data-level="6.3.1" data-path="causal-inference.html"><a href="causal-inference.html#stable-unit-treatment-value-assignment"><i class="fa fa-check"></i><b>6.3.1</b> Stable Unit Treatment Value Assignment</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="causal-inference.html"><a href="causal-inference.html#ignorable-assignment-mechanisims"><i class="fa fa-check"></i><b>6.4</b> Ignorable Assignment Mechanisims</a><ul>
<li class="chapter" data-level="6.4.1" data-path="causal-inference.html"><a href="causal-inference.html#the-perfect-doctor-example"><i class="fa fa-check"></i><b>6.4.1</b> The Perfect Doctor Example</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="causal-inference.html"><a href="causal-inference.html#questions-3"><i class="fa fa-check"></i><b>6.5</b> Questions</a></li>
<li class="chapter" data-level="6.6" data-path="causal-inference.html"><a href="causal-inference.html#answers-to-questions"><i class="fa fa-check"></i><b>6.6</b> Answers to Questions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html"><i class="fa fa-check"></i><b>7</b> Design of Observational Studies</a><ul>
<li class="chapter" data-level="7.1" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#what-is-an-observational-study"><i class="fa fa-check"></i><b>7.1</b> What is an observational study?</a></li>
<li class="chapter" data-level="7.2" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#designing-and-observational-study"><i class="fa fa-check"></i><b>7.2</b> Designing and Observational Study</a></li>
<li class="chapter" data-level="7.3" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#example---epidemiologic-follow-up-study"><i class="fa fa-check"></i><b>7.3</b> Example - Epidemiologic Follow-up Study</a></li>
<li class="chapter" data-level="7.4" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#propensity-score-1"><i class="fa fa-check"></i><b>7.4</b> Propensity Score</a><ul>
<li class="chapter" data-level="7.4.1" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#propensity-score-examples"><i class="fa fa-check"></i><b>7.4.1</b> Propensity Score Examples</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#estimating-the-propensity-score-in-an-observational-study"><i class="fa fa-check"></i><b>7.5</b> Estimating the propensity score in an observational study</a></li>
<li class="chapter" data-level="7.6" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#the-balancing-property-of-the-propensity-score"><i class="fa fa-check"></i><b>7.6</b> The balancing property of the propensity score</a></li>
<li class="chapter" data-level="7.7" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#imbalance-versus-overlap"><i class="fa fa-check"></i><b>7.7</b> Imbalance versus Overlap</a><ul>
<li class="chapter" data-level="7.7.1" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#example-from-the-nhefs"><i class="fa fa-check"></i><b>7.7.1</b> Example from the NHEFS</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#propensity-score-and-ignorable-treatment-assignment"><i class="fa fa-check"></i><b>7.8</b> Propensity Score and Ignorable Treatment Assignment</a></li>
<li class="chapter" data-level="7.9" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#propensity-score-methods-to-reduce-bias-in-observational-studies"><i class="fa fa-check"></i><b>7.9</b> Propensity Score Methods to Reduce Bias in Observational Studies</a><ul>
<li class="chapter" data-level="7.9.1" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#propensity-score-matching-matching"><i class="fa fa-check"></i><b>7.9.1</b> Propensity Score Matching Matching</a></li>
<li class="chapter" data-level="7.9.2" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#propensity-score-stratification"><i class="fa fa-check"></i><b>7.9.2</b> Propensity score stratification</a></li>
<li class="chapter" data-level="7.9.3" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#multivariate-adjustment-using-the-propensity-score"><i class="fa fa-check"></i><b>7.9.3</b> Multivariate adjustment using the propensity score</a></li>
<li class="chapter" data-level="7.9.4" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#comparing-the-three-methods"><i class="fa fa-check"></i><b>7.9.4</b> Comparing the three methods</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#questions-4"><i class="fa fa-check"></i><b>7.10</b> Questions</a></li>
<li class="chapter" data-level="7.11" data-path="design-of-observational-studies.html"><a href="design-of-observational-studies.html#answers-to-questions-1"><i class="fa fa-check"></i><b>7.11</b> Answers to Questions</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html"><i class="fa fa-check"></i><b>8</b> Completely Randomized Designs: Comparing More Than Two Treatments</a><ul>
<li class="chapter" data-level="8.1" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#anova---comparing-more-than-two-groups"><i class="fa fa-check"></i><b>8.1</b> ANOVA - Comparing more than two groups</a></li>
<li class="chapter" data-level="8.2" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#analysis-of-variance-anova-table"><i class="fa fa-check"></i><b>8.2</b> Analysis of Variance (ANOVA) table</a></li>
<li class="chapter" data-level="8.3" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#the-anova-identity"><i class="fa fa-check"></i><b>8.3</b> The ANOVA identity</a><ul>
<li class="chapter" data-level="8.3.1" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#example---blood-coagulation-study"><i class="fa fa-check"></i><b>8.3.1</b> Example - Blood coagulation study</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#general-anova"><i class="fa fa-check"></i><b>8.4</b> General ANOVA</a></li>
<li class="chapter" data-level="8.5" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#anova-assumptions"><i class="fa fa-check"></i><b>8.5</b> ANOVA Assumptions</a><ul>
<li class="chapter" data-level="8.5.1" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#example---checking-the-assumptions-in-the-blood-coagualtion-study"><i class="fa fa-check"></i><b>8.5.1</b> Example - checking the assumptions in the blood coagualtion study</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#coding-qualitative-predictors-in-regression-models"><i class="fa fa-check"></i><b>8.6</b> Coding Qualitative Predictors in Regression Models</a><ul>
<li class="chapter" data-level="8.6.1" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#dummy-coding"><i class="fa fa-check"></i><b>8.6.1</b> Dummy Coding</a></li>
<li class="chapter" data-level="8.6.2" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#deviation-coding"><i class="fa fa-check"></i><b>8.6.2</b> Deviation Coding</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#estimating-treatment-effects-using-least-squares"><i class="fa fa-check"></i><b>8.7</b> Estimating Treatment Effects using Least Squares</a></li>
<li class="chapter" data-level="8.8" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#using-the-lm-function-in-r-to-estimate-treatment-effects"><i class="fa fa-check"></i><b>8.8</b> Using the <code>lm()</code> Function in R to Estimate Treatment Effects</a></li>
<li class="chapter" data-level="8.9" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#questions-1-1"><i class="fa fa-check"></i><b>8.9</b> Questions-1</a></li>
<li class="chapter" data-level="8.10" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#multiple-comparisons"><i class="fa fa-check"></i><b>8.10</b> Multiple Comparisons</a><ul>
<li class="chapter" data-level="8.10.1" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#the-bonferroni-method"><i class="fa fa-check"></i><b>8.10.1</b> The Bonferroni Method</a></li>
<li class="chapter" data-level="8.10.2" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#the-tukey-method"><i class="fa fa-check"></i><b>8.10.2</b> The Tukey Method</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#sample-size-for-anova---designing-a-study-to-compare-more-than-two-treatments"><i class="fa fa-check"></i><b>8.11</b> Sample size for ANOVA - Designing a study to compare more than two treatments</a><ul>
<li class="chapter" data-level="8.11.1" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#direct-calculation-of-power-using-r"><i class="fa fa-check"></i><b>8.11.1</b> Direct calculation of Power using R</a></li>
<li class="chapter" data-level="8.11.2" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#calculating-power-and-sample-size-using-the-pwr-library-in-r"><i class="fa fa-check"></i><b>8.11.2</b> Calculating Power and Sample Size using the <code>pwr</code> library in R</a></li>
<li class="chapter" data-level="8.11.3" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#calculating-power-using-using-simulation"><i class="fa fa-check"></i><b>8.11.3</b> Calculating Power using using Simulation</a></li>
</ul></li>
<li class="chapter" data-level="8.12" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#questions-2-1"><i class="fa fa-check"></i><b>8.12</b> Questions-2</a></li>
<li class="chapter" data-level="8.13" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#answers-to-questions-1-1"><i class="fa fa-check"></i><b>8.13</b> Answers to Questions-1</a></li>
<li class="chapter" data-level="8.14" data-path="completely-randomized-designs-comparing-more-than-two-treatments.html"><a href="completely-randomized-designs-comparing-more-than-two-treatments.html#answers-to-questions-2"><i class="fa fa-check"></i><b>8.14</b> Answers to Questions-2</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html"><i class="fa fa-check"></i><b>9</b> Randomized Block Designs</a><ul>
<li class="chapter" data-level="9.1" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#anova-table-for-randomized-block-designs"><i class="fa fa-check"></i><b>9.1</b> ANOVA Table for Randomized Block Designs</a></li>
<li class="chapter" data-level="9.2" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#the-anova-identity-for-randomized-block-designs"><i class="fa fa-check"></i><b>9.2</b> The ANOVA identity for Randomized Block Designs</a><ul>
<li class="chapter" data-level="9.2.1" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#degrees-of-freedom"><i class="fa fa-check"></i><b>9.2.1</b> Degrees of freedom</a></li>
<li class="chapter" data-level="9.2.2" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#penicillin-manufacturing-example"><i class="fa fa-check"></i><b>9.2.2</b> Penicillin Manufacturing Example</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#the-linear-model-for-randomized-block-design"><i class="fa fa-check"></i><b>9.3</b> The Linear Model for Randomized Block Design</a><ul>
<li class="chapter" data-level="9.3.1" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#checking-statistical-assumptions"><i class="fa fa-check"></i><b>9.3.1</b> Checking statistical assumptions</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#application-of-blocking-to-achieve-balanced-randomization-permuted-block-randomization"><i class="fa fa-check"></i><b>9.4</b> Application of Blocking to Achieve Balanced Randomization: Permuted Block Randomization</a></li>
<li class="chapter" data-level="9.5" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#latin-square-designs"><i class="fa fa-check"></i><b>9.5</b> Latin square designs</a></li>
<li class="chapter" data-level="9.6" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#general-latin-square-designs"><i class="fa fa-check"></i><b>9.6</b> General Latin Square Designs</a></li>
<li class="chapter" data-level="9.7" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#graeco-latin-square-designs"><i class="fa fa-check"></i><b>9.7</b> Graeco-Latin Square Designs</a></li>
<li class="chapter" data-level="9.8" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#hyper-graeco-latin-square-designs"><i class="fa fa-check"></i><b>9.8</b> Hyper-Graeco-Latin Square Designs</a></li>
<li class="chapter" data-level="9.9" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#balanced-incomplete-block-designs"><i class="fa fa-check"></i><b>9.9</b> Balanced incomplete block designs</a></li>
<li class="chapter" data-level="9.10" data-path="randomized-block-designs.html"><a href="randomized-block-designs.html#questions-5"><i class="fa fa-check"></i><b>9.10</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html"><i class="fa fa-check"></i><b>10</b> Factorial Designs at Two Levels - <span class="math inline">\(2^k\)</span> Designs</a><ul>
<li class="chapter" data-level="10.1" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#difference-between-anova-and-factorial-designs"><i class="fa fa-check"></i><b>10.1</b> Difference between ANOVA and Factorial Designs</a></li>
<li class="chapter" data-level="10.2" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#performing-a-2k-factorial-design"><i class="fa fa-check"></i><b>10.2</b> Performing a <span class="math inline">\(2^k\)</span> Factorial Design</a></li>
<li class="chapter" data-level="10.3" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#cube-plots"><i class="fa fa-check"></i><b>10.3</b> Cube plots</a></li>
<li class="chapter" data-level="10.4" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#factorial-effects"><i class="fa fa-check"></i><b>10.4</b> Factorial effects</a><ul>
<li class="chapter" data-level="10.4.1" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#main-effects"><i class="fa fa-check"></i><b>10.4.1</b> Main effects</a></li>
<li class="chapter" data-level="10.4.2" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#interaction-effects"><i class="fa fa-check"></i><b>10.4.2</b> Interaction effects</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#replication-in-factorial-designs"><i class="fa fa-check"></i><b>10.5</b> Replication in factorial designs</a></li>
<li class="chapter" data-level="10.6" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#estimate-of-the-error-variance-and-standard-error-of-effects-from-replicated-runs"><i class="fa fa-check"></i><b>10.6</b> Estimate of the error variance and standard error of effects from replicated runs</a></li>
<li class="chapter" data-level="10.7" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#interpretation-of-results"><i class="fa fa-check"></i><b>10.7</b> Interpretation of results</a></li>
<li class="chapter" data-level="10.8" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#interaction-plots"><i class="fa fa-check"></i><b>10.8</b> Interaction plots</a></li>
<li class="chapter" data-level="10.9" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#linear-model-for-a-2k-factorial-design"><i class="fa fa-check"></i><b>10.9</b> Linear Model for a <span class="math inline">\(2^k\)</span> Factorial Design</a></li>
<li class="chapter" data-level="10.10" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#advantages-of-factorial-designs-over-one-factor-at-a-time-designs"><i class="fa fa-check"></i><b>10.10</b> Advantages of factorial designs over one-factor-at-a-time designs</a></li>
<li class="chapter" data-level="10.11" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#normal-plots-in-unreplicated-factorial-designs"><i class="fa fa-check"></i><b>10.11</b> Normal Plots in Unreplicated Factorial Designs</a><ul>
<li class="chapter" data-level="10.11.1" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#review-of-normal-quantile-plots"><i class="fa fa-check"></i><b>10.11.1</b> Review of Normal Quantile Plots</a></li>
<li class="chapter" data-level="10.11.2" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#example---24-design-for-studying-a-chemical-reaction"><i class="fa fa-check"></i><b>10.11.2</b> Example - <span class="math inline">\(2^4\)</span> design for studying a chemical reaction</a></li>
</ul></li>
<li class="chapter" data-level="10.12" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#half-normal-plots"><i class="fa fa-check"></i><b>10.12</b> Half-Normal Plots</a></li>
<li class="chapter" data-level="10.13" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#lenths-method-testing-significance-for-experiments-without-variance-estimates"><i class="fa fa-check"></i><b>10.13</b> Lenth’s method: testing significance for experiments without variance estimates</a></li>
<li class="chapter" data-level="10.14" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#questions-6"><i class="fa fa-check"></i><b>10.14</b> Questions</a></li>
<li class="chapter" data-level="10.15" data-path="factorial-designs-at-two-levels-2k-designs.html"><a href="factorial-designs-at-two-levels-2k-designs.html#answers-to-questions-3"><i class="fa fa-check"></i><b>10.15</b> Answers to Questions</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="blocking-factorial-designs.html"><a href="blocking-factorial-designs.html"><i class="fa fa-check"></i><b>11</b> Blocking Factorial Designs</a><ul>
<li class="chapter" data-level="11.0.1" data-path="blocking-factorial-designs.html"><a href="blocking-factorial-designs.html#effect-hierarchy-principle"><i class="fa fa-check"></i><b>11.0.1</b> Effect hierarchy principle</a></li>
<li class="chapter" data-level="11.0.2" data-path="blocking-factorial-designs.html"><a href="blocking-factorial-designs.html#generation-of-orthogonal-blocks"><i class="fa fa-check"></i><b>11.0.2</b> Generation of Orthogonal Blocks</a></li>
<li class="chapter" data-level="11.0.3" data-path="blocking-factorial-designs.html"><a href="blocking-factorial-designs.html#an-example-of-how-not-to-block"><i class="fa fa-check"></i><b>11.0.3</b> An example of how not to block</a></li>
<li class="chapter" data-level="11.1" data-path="blocking-factorial-designs.html"><a href="blocking-factorial-designs.html#generators-and-defining-relations"><i class="fa fa-check"></i><b>11.1</b> Generators and Defining Relations</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html"><i class="fa fa-check"></i><b>12</b> Fractional factorial designs</a><ul>
<li class="chapter" data-level="12.1" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#example---effect-of-five-factors-on-six-properties-of-film-in-eight-runs"><i class="fa fa-check"></i><b>12.1</b> Example - Effect of five factors on six properties of film in eight runs</a></li>
<li class="chapter" data-level="12.2" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#effect-aliasing-and-design-resolution"><i class="fa fa-check"></i><b>12.2</b> Effect Aliasing and Design Resolution</a></li>
<li class="chapter" data-level="12.3" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#example---leaf-spring-experiment"><i class="fa fa-check"></i><b>12.3</b> Example - Leaf Spring Experiment</a></li>
<li class="chapter" data-level="12.4" data-path="fractional-factorial-designs.html"><a href="fractional-factorial-designs.html#example---baking-cookies"><i class="fa fa-check"></i><b>12.4</b> Example - Baking Cookies</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="split-plot-designs.html"><a href="split-plot-designs.html"><i class="fa fa-check"></i><b>13</b> Split-Plot Designs</a><ul>
<li class="chapter" data-level="13.1" data-path="split-plot-designs.html"><a href="split-plot-designs.html#anova-table-for-split-plot-experiment"><i class="fa fa-check"></i><b>13.1</b> ANOVA table for split plot experiment</a></li>
<li class="chapter" data-level="13.2" data-path="split-plot-designs.html"><a href="split-plot-designs.html#split-plot-anova---how-not-to-do-it"><i class="fa fa-check"></i><b>13.2</b> Split plot ANOVA - How not to do it</a></li>
<li class="chapter" data-level="13.3" data-path="split-plot-designs.html"><a href="split-plot-designs.html#split-plot-anova---how-to-do-it"><i class="fa fa-check"></i><b>13.3</b> Split plot ANOVA - How to do it</a></li>
<li class="chapter" data-level="13.4" data-path="split-plot-designs.html"><a href="split-plot-designs.html#so-what-is-a-split-plot"><i class="fa fa-check"></i><b>13.4</b> So, what is a split plot?</a><ul>
<li class="chapter" data-level="13.4.1" data-path="split-plot-designs.html"><a href="split-plot-designs.html#randomizing-a-split-plot-experiment"><i class="fa fa-check"></i><b>13.4.1</b> Randomizing a Split Plot experiment</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="split-plot-designs.html"><a href="split-plot-designs.html#questions-7"><i class="fa fa-check"></i><b>13.5</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Design of Experiments and Observational Studies</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="how-many-experimental-units-are-required-to-compare-two-treatments" class="section level1">
<h1><span class="header-section-number">5</span> How Many Experimental Units are Required to Compare Two Treatments?</h1>
<p>Suppose that a company would like to compare two versions of a web page to see if one version leads to higher sales. How many people should visit the each version of the website? A pharmaceutical company is required to compare a novel treatment for cancer against the standard treatment to investigate if patient mortality decreases when receiving the novel treatment. To study how physical expression influences psychological processes such as risk taking subjects were randomized to two groups where one group was instructed to pose in a high-power position and the second group in a low-power position.</p>
<p>In each of these examples experimental units (e.g., human subjects) were randomly assigned to two groups to investigate the causal effects of a treatment. How many subjects should be assigned to each group?</p>
<div id="clinical-trials" class="section level2">
<h2><span class="header-section-number">5.1</span> Clinical Trials</h2>
<p>Clinical trials are prospective intervention studies with human subjects to investigate experimental drugs, new treatments, medical devices, or clinical procedures (<span class="citation">Yin (<a href="#ref-yin2013clinical" role="doc-biblioref">2013</a>)</span>).</p>
<p>There are typically fours phases of clinical trials.</p>
<div id="phases-of-clinical-trials" class="section level3">
<h3><span class="header-section-number">5.1.1</span> Phases of clinical trials</h3>
<p>The phases of clinical trials that might be involved in developing a new drug for a certain cancer are described below.</p>
<p><strong>Preclinical studies:</strong> In vitro (e.g. slides, test tubes) and in vivo (living organism such as rodents) studies on wide range of doses of experimental agents. This stage of study provides preliminary toxicity and efficacy data including pharmacokinetics (PK) and pharmacodynamics (PD) information.</p>
<p><strong>Phase I:</strong> Usually first study in humans to investigate the toxicity and side effects of the new agent. Identify MTD.</p>
<p><strong>Phase II:</strong> Assess if drug has sufficient efficacy. The drug is usually administered around the MTD. If drug does not show efficacy or is too toxic then further testing is discontinued.</p>
<p><strong>Phase III:</strong> If drug passes phase II testing then it is compared to the current standard of care or placebo. These are long-term, large scale randomized studies that may involve hundreds or thousands of patients.</p>
<p>If the drug is proven to be effective (e.g. two positive phase III trials required for FDA approval) the company will file an application with regulatory agencies to sell the drug.
If approved then the drug will be available to the general population in the country where it was approved.</p>
<p><strong>Phase IV:</strong> After approval a study might follow a large number of patients over a longer period of time to monitor side effects and drug interactions. For example, findings from these studies might add a warning label to the drug.</p>
<p>Some comments:</p>
<ul>
<li>The four phases are usually conducted sequentially and separately.</li>
<li>Each trial requires an independent study design and a study protocol.</li>
<li>Every aspect of trial design, monitoring, and data analysis call upon statistical methods.</li>
<li>In randomized clinical trials a treatment group is often referred to as an <strong>arm</strong>.</li>
</ul>
<p>According to the <a href="https://clinicaltrials.gov/ct2/about-studies/glossary#A">ClinicalTrials.gov</a> an arm is defined as:</p>
<blockquote>
<p>A group or subgroup of participants in a clinical trial that receives specific interventions, or no intervention, according to the study protocol. This is decided before the trial begins.</p>
</blockquote>
<p><strong>How can causation be assessed using a randomized design?</strong></p>
<ul>
<li><p>Suppose that patients are randomized in a two arm clinical trial where one of the arms is the standard treatment and the other arm is an experimental treatment and there is a statistically significant difference in the outcome between the two arms showing the experimental treatment is more efficacious.</p></li>
<li><p>The interpretation is that the experimental treatment <em>caused</em> patients to have a better outcome since the only difference between the two arms is the treatment. Randomization is supposed to ensure that the groups will be similar with respect to all the factors measured in the study and all the factors that are not measured.</p></li>
</ul>
<div id="how-many-patients-should-be-enrolled-in-a-phase-iii-clinical-trial" class="section level4">
<h4><span class="header-section-number">5.1.1.1</span> How many patients should be enrolled in a Phase III clinical trial?</h4>
<blockquote>
<p>If an experimental agent exhibits adequate short-term therapeutic effects in a phase II trial, the drug will be moved forward to a phase III study for confirmative testing of its long-term effectiveness. Phase III clinical trials are randomized and controlled studies that directly compare the investigational drug with the current “gold standard” treatment or a placebo when there is no standard of care. The sample size of a phase III trial is large, usually ranging from hundreds up to thousands of participants … Due to their enormous sizes, large scales, and long follow-ups, phase III trials are the most costly comparative studies to evaluate the drug’s efficacy. (pg. 159, <span class="citation">Yin (<a href="#ref-yin2013clinical" role="doc-biblioref">2013</a>)</span>)</p>
</blockquote>
<ul>
<li>In a phase III trial sample size is the most critical component of the study design. The sample size has implications for how many subjects will be exposed to a drug that has no proven efficacy.</li>
<li>The investigator needs to specify type I, II error rates, and the effect sizes.</li>
<li>Standard practice is to compute the smallest sample size required to detect a clinically important/significant treatment difference with sufficient.</li>
<li>If the sample size is too small then the trial might fail to discover a truly effective drug because the statistical test cannot reach the significance level (5%) due to a lack of power.</li>
<li>If the sample size is overestimated then resources wasted and drug development delayed since patient enrollment is often the main factor in time to complete a trial.</li>
</ul>
</div>
</div>
</div>
<div id="statistical-hypotheses-and-the-number-of-experimental-units" class="section level2">
<h2><span class="header-section-number">5.2</span> Statistical Hypotheses and the Number of Experimental Units</h2>
<p>Suppose that subjects are randomized to treatments A or B with equal probability.
Let <span class="math inline">\(\mu_A\)</span> be the mean response in the group receiving drug A and <span class="math inline">\(\mu_B\)</span> be the mean response in the group receiving drug B.
The null hypothesis is that there is no difference between A and B, the alternative claims there is a clinically meaningful difference between them.</p>
<p><span class="math display">\[H_0:\mu_A=\mu_B \thinspace \text{ versus } \thinspace H_1:\mu_A \ne \mu_B \]</span></p>
<p>The type I error rate is defined as:</p>
<p><span class="math display">\[\begin{aligned}
\alpha &amp;=P\left(\text{type I error}\right) \\
       &amp;=P\left(\text{Reject } H_0|H_0 \text{ is true}\right).\\
\end{aligned}\]</span></p>
<p>The type II error rate is defined as:</p>
<p><span class="math display">\[\begin{aligned}
\beta&amp;=P\left(\text{type II error}\right) \\
     &amp;=P\left(\text{Accept }H_0|H_1 \text{ is true}\right).   
\end{aligned}\]</span></p>
<p>Power is defined as:
<span class="math display">\[ \begin{aligned}
\text {power} &amp;= 1-\beta \\
              &amp;= 1-P\left(\text{Accept }H_0|H_1 \text{ is true}\right) \\
              &amp;= P\left(\text{Reject } H_0|H_1 \text{ is true}\right).
\end{aligned}\]</span></p>
</div>
<div id="power-of-the-one-sample-z-test" class="section level2">
<h2><span class="header-section-number">5.3</span> Power of the One Sample z-test</h2>
<p>Let <span class="math inline">\(X_1,...,X_n\)</span> be a random sample from a <span class="math inline">\(N(\mu,\sigma^2)\)</span> distribution. A test of the hypothesis</p>
<p><span class="math display">\[H_0:\mu=\mu_0 \thinspace \text{ versus } \thinspace H_1:\mu \ne \mu_0 \]</span></p>
<p>will reject at level <span class="math inline">\(\alpha\)</span> if and only if</p>
<p><span class="math display">\[ \left|\frac{{\bar X} - \mu_0}{\sigma/{\sqrt{n}}} \right| \ge z_{\alpha/2},\]</span></p>
<p>or</p>
<p><span class="math display">\[ \left|{\bar X} -\mu_0 \right| \ge \frac{\sigma}{\sqrt{n}} z_{\alpha/2},\]</span></p>
<p>where <span class="math inline">\(z_{\alpha/2}\)</span> is the <span class="math inline">\(100(1-\alpha/2)^{th}\)</span> percentile of the <span class="math inline">\(N(0,1)\)</span>.</p>
<p>The power of the test at <span class="math inline">\(\mu=\mu_1\)</span> is</p>
<p><span class="math display">\[\begin{aligned}
1-\beta &amp;= 1-P\left(\text{type II error}\right) \\
        &amp;= P\left(\text{Reject } H_0|H_1 \text{ is true}\right) \\
        &amp;= P\left(\text{Reject } H_0|\mu=\mu_1\right) \\
        &amp;= P\left(\left|{\bar X} -\mu_0 \right| \ge \frac{\sigma}{\sqrt{n}} z_{\alpha/2}|\mu=\mu_1\right) \\
        &amp;= P\left({\bar X} -\mu_0  \ge \frac{\sigma}{\sqrt{n}} z_{\alpha/2}|\mu=\mu_1\right) + P\left({\bar X} -\mu_0  &lt; \frac{-\sigma}{\sqrt{n}} z_{\alpha/2}|\mu=\mu_1\right) \\
\end{aligned}\]</span></p>
<p>Subtract the mean <span class="math inline">\(\mu_1\)</span> and divide by <span class="math inline">\(\sigma/\sqrt{n}\)</span> to obtain:</p>
<p><span class="math display">\[ 1-\beta = 1-\Phi\left( z_{\alpha/2}-\left(\frac{\mu_1-\mu_0}{\sigma/\sqrt{n}}\right) \right)+\Phi\left( -z_{\alpha/2}-\left(\frac{\mu_1-\mu_0}{\sigma/\sqrt{n}}\right) \right),\]</span></p>
<p>where <span class="math inline">\(\Phi(\cdot)\)</span> is the <span class="math inline">\(N(0,1)\)</span> CDF.</p>
<div id="exercises-2" class="section level3">
<h3><span class="header-section-number">5.3.1</span> Exercises</h3>
<ol style="list-style-type: decimal">
<li>What is the limit of the power function as:</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><span class="math inline">\(n \rightarrow \infty\)</span></li>
<li><span class="math inline">\(\mu_1 \rightarrow \mu_0\)</span></li>
</ol>
<p>Answers:(a) 1; (b) <span class="math inline">\(\alpha\)</span>.</p>
</div>
<div id="calculating-the-power-of-the-one-sample-z-test-using-r" class="section level3">
<h3><span class="header-section-number">5.3.2</span> Calculating the Power of the One Sample z-test using R</h3>
<p>The power function for a one-sample z-test can be calculated using R.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb136-1" title="1">pow.z.test &lt;-<span class="st"> </span><span class="cf">function</span>(alpha,mu1,mu0,sigma,n){</a>
<a class="sourceLine" id="cb136-2" title="2">  arg1 &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>)<span class="op">-</span>(mu1<span class="op">-</span>mu0)<span class="op">/</span>(sigma<span class="op">/</span><span class="kw">sqrt</span>(n))</a>
<a class="sourceLine" id="cb136-3" title="3">  arg2 &lt;-<span class="st"> </span><span class="dv">-1</span><span class="op">*</span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>)<span class="op">-</span>(mu1<span class="op">-</span>mu0)<span class="op">/</span>(sigma<span class="op">/</span><span class="kw">sqrt</span>(n))</a>
<a class="sourceLine" id="cb136-4" title="4">  <span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(arg1)<span class="op">+</span><span class="kw">pnorm</span>(arg2)</a>
<a class="sourceLine" id="cb136-5" title="5">}</a></code></pre></div>
<p>For example the power of the test</p>
<p><span class="math display">\[H_0:\mu = 0 \thinspace \text{ versus } \thinspace H_1:\mu = 0.2\]</span> with <span class="math inline">\(n = 30,\sigma = 0.2, \alpha = 0.05\)</span> can be calculated by calling the above function.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" title="1"><span class="kw">pow.z.test</span>(.<span class="dv">05</span>,.<span class="dv">15</span>,<span class="dv">0</span>,.<span class="dv">2</span>,<span class="dv">30</span>) </a></code></pre></div>
<pre><code>[1] 0.9841413</code></pre>
<p>This means that with <span class="math inline">\(n = 30\)</span> experimental units there is a 0.98 probability that the z-test will detect a mean of 0.2 when <span class="math inline">\(\sigma = 0.2, \alpha = 0.05\)</span>.</p>
</div>
</div>
<div id="power-of-the-one-sample-t-test" class="section level2">
<h2><span class="header-section-number">5.4</span> Power of the one-sample t-test</h2>
<p>Let <span class="math inline">\(X_1,...,X_n\)</span> be a random sample from a <span class="math inline">\(N(\mu,\sigma^2)\)</span> distribution. A test of the hypothesis</p>
<p><span class="math display">\[H_0:\mu=\mu_0 \thinspace \text{ versus } \thinspace H_1:\mu \ne \mu_0 \]</span></p>
<p>will reject at level <span class="math inline">\(\alpha\)</span> if and only if</p>
<p><span class="math display">\[ \left|\frac{{\bar X} - \mu_0}{S/{\sqrt{n}}} \right| \ge t_{n-1, \alpha/2},\]</span></p>
<p>where <span class="math inline">\(t_{n-1, \alpha/2}\)</span> is the <span class="math inline">\(100(1-\alpha/2)^{th}\)</span> percentile of the <span class="math inline">\(t_{n-1}\)</span>.</p>
<p>It can be shown that</p>
<p><span class="math display">\[\sqrt{n} \left[\frac{{\bar X}-\mu_0}{S}\right] =  \frac{Z + \gamma}{\sqrt{V/(n-1)}},\]</span></p>
<p>where,</p>
<p><span class="math display">\[\begin{aligned}
Z &amp;= \frac{\sqrt{n}({\bar X}-\mu_1)}{\sigma} \\
\gamma &amp;=  \frac{\sqrt{n}(\mu_1-\mu_0)}{\sigma} \\
V &amp;= \frac{(n-1)}{\sigma^2} S^2.
\end{aligned}\]</span></p>
<p><span class="math inline">\(Z \sim N(0,1)\)</span> and <span class="math inline">\(V \sim \chi^2_{n-1}\)</span> and <span class="math inline">\(Z\)</span> is independent of <span class="math inline">\(V\)</span>.</p>
<p>If <span class="math inline">\(\gamma = 0\)</span> then then <span class="math inline">\(\sqrt{n} \left[\frac{{\bar X}-\mu_0}{S}\right] \sim t_{n-1}\)</span>. But, if <span class="math inline">\(\gamma \ne 0\)</span> then <span class="math inline">\(\sqrt{n} \left[\frac{{\bar X}-\mu_0}{S}\right] \sim t_{n-1, \gamma}\)</span>, where <span class="math inline">\(t_{n-1, \gamma}\)</span> is the non-central t-distribution with non-centrality parameter <span class="math inline">\(\gamma\)</span>. If <span class="math inline">\(\gamma = 0\)</span> this is sometimes called the central t-distribution.</p>
<p>A plot of the central (<span class="math inline">\(\gamma = 0\)</span>) and non-central t are shown in the plot below.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" title="1"><span class="co">#Plot of noncentral t and central t</span></a>
<a class="sourceLine" id="cb139-2" title="2">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="op">-</span><span class="dv">6</span>,<span class="dv">6</span>,<span class="dt">by =</span> <span class="fl">0.01</span>)</a>
<a class="sourceLine" id="cb139-3" title="3"><span class="kw">plot</span>(x,<span class="kw">dt</span>(x,<span class="dv">10</span>,<span class="dv">0</span>),<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">ylab =</span> <span class="st">&quot;t-density&quot;</span>,<span class="dt">col =</span> <span class="st">&quot;black&quot;</span>,</a>
<a class="sourceLine" id="cb139-4" title="4">     <span class="dt">xlab =</span> <span class="st">&quot;x&quot;</span>,<span class="dt">main =</span> <span class="st">&quot;Noncentral t-distribution&quot;</span>)</a>
<a class="sourceLine" id="cb139-5" title="5"><span class="kw">points</span>(x,<span class="kw">dt</span>(x,<span class="dv">10</span>,<span class="dv">1</span>),<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">lty =</span> <span class="dv">2</span>,<span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb139-6" title="6"><span class="kw">points</span>(x,<span class="kw">dt</span>(x,<span class="dv">10</span>,<span class="dv">2</span>),<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">lty =</span> <span class="dv">3</span>,<span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb139-7" title="7"><span class="kw">legend</span>(<span class="st">&quot;topleft&quot;</span>,</a>
<a class="sourceLine" id="cb139-8" title="8">       <span class="dt">legend =</span> <span class="kw">c</span>(<span class="kw">expression</span>(gamma <span class="op">==</span><span class="st"> </span><span class="dv">0</span>),</a>
<a class="sourceLine" id="cb139-9" title="9">                <span class="kw">expression</span>(gamma <span class="op">==</span><span class="st"> </span><span class="dv">1</span>),<span class="kw">expression</span>(gamma<span class="op">==</span><span class="dv">2</span>)),</a>
<a class="sourceLine" id="cb139-10" title="10">                <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>),<span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;red&quot;</span>))</a></code></pre></div>
<p><img src="04-powersampsize_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>The power of the test at <span class="math inline">\(\mu=\mu_1\)</span> is</p>
<p><span class="math display">\[\begin{aligned}
1-\beta &amp;= 1-P\left(\text{type II error}\right) \\
        &amp;= P\left(\text{Reject } H_0|H_1 \text{ is true}\right) \\
        &amp;= P\left(\text{Reject } H_0|\mu=\mu_1\right) \\
        &amp;= P\left(\left|\frac {{\bar X} -\mu_0} {\frac{S}{\sqrt{n}}} \right| \ge  t_{n-1, \alpha/2}|\mu=\mu_1\right) \\
        &amp;=  P\left(\frac {{\bar X} -\mu_0} {\frac{S}{\sqrt{n}}}  \ge  t_{n-1, \alpha/2}|\mu=\mu_1\right) + P\left(\frac {{\bar X} -\mu_0} {\frac{S}{\sqrt{n}}} &lt; - t_{n-1, \alpha/2}|\mu=\mu_1\right) \\
        &amp;= P(t_{n-1,\gamma}\ge t_{n-1,\alpha/2})+P(t_{n-1,\gamma}&lt; -t_{n-1,\alpha/2})
\end{aligned}\]</span></p>
<div id="calculating-the-power-of-the-one-sample-t-test-using-r" class="section level3">
<h3><span class="header-section-number">5.4.1</span> Calculating the Power of the One Sample t-test using R</h3>
<div id="write-a-custom-function-to-calculate-power" class="section level4">
<h4><span class="header-section-number">5.4.1.1</span> Write a Custom Function to Calculate Power</h4>
<p>The following function calculates the power function for the one-sample t-test in R:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb140-1" title="1">onesampttestpow &lt;-<span class="st"> </span><span class="cf">function</span>(alpha,n, mu0, mu1,sigma)</a>
<a class="sourceLine" id="cb140-2" title="2">{delta &lt;-<span class="st"> </span>mu1<span class="op">-</span>mu0</a>
<a class="sourceLine" id="cb140-3" title="3">t.crit &lt;-<span class="kw">qt</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>,n<span class="dv">-1</span>)</a>
<a class="sourceLine" id="cb140-4" title="4">t.gamma &lt;-<span class="st"> </span><span class="kw">sqrt</span>(n)<span class="op">*</span>(delta<span class="op">/</span>sigma)</a>
<a class="sourceLine" id="cb140-5" title="5">t.power &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">pt</span>(t.crit,n<span class="dv">-1</span>,<span class="dt">ncp =</span> t.gamma)<span class="op">+</span><span class="kw">pt</span>(<span class="op">-</span>t.crit,n<span class="dv">-1</span>,<span class="dt">ncp =</span> t.gamma)</a>
<a class="sourceLine" id="cb140-6" title="6"><span class="kw">return</span>(t.power)</a>
<a class="sourceLine" id="cb140-7" title="7">}</a></code></pre></div>
<p>For example the power of the t-test for testing</p>
<p><span class="math display">\[H_0:\mu = 0 \thinspace \text{ versus } \thinspace H_1:\mu = 0.15\]</span> with <span class="math inline">\(n = 10,\sigma = 0.2, \alpha = 0.05\)</span> can be calculated by calling the above function is</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" title="1"><span class="kw">onesampttestpow</span>(.<span class="dv">05</span>,<span class="dv">10</span>,<span class="dv">0</span>,.<span class="dv">15</span>,<span class="fl">0.2</span>)</a></code></pre></div>
<pre><code>[1] 0.5619533</code></pre>
</div>
<div id="use-power.t.test-to-calculate-power" class="section level4">
<h4><span class="header-section-number">5.4.1.2</span> Use <code>power.t.test()</code> to Calculate Power</h4>
<p>There is built-in function in R that can calculate the power of t-test <code>power.t.test()</code>. Using this function on the previous example we get</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb143-1" title="1"><span class="kw">power.t.test</span>(<span class="dt">n =</span> <span class="dv">10</span>,<span class="dt">delta =</span> <span class="fl">0.15</span>,<span class="dt">sd =</span> <span class="fl">0.2</span>,<span class="dt">sig.level =</span> <span class="fl">0.05</span>,<span class="dt">type =</span> <span class="st">&quot;one.sample&quot;</span> )</a></code></pre></div>
<pre><code>
     One-sample t test power calculation 

              n = 10
          delta = 0.15
             sd = 0.2
      sig.level = 0.05
          power = 0.5619339
    alternative = two.sided</code></pre>
<p>Exactly one of the parameters <code>n</code>, <code>delta</code>, <code>power</code>, <code>sd</code>, and <code>sig.level</code> must be passed as <code>NULL</code>, and that parameter is determined from the others. In this example the function calculates power given the other parameters. If sample size is required for, say, 80% power then use</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb145-1" title="1"><span class="kw">power.t.test</span>(<span class="dt">power =</span> <span class="fl">0.8</span>,<span class="dt">delta =</span> <span class="fl">0.15</span>,<span class="dt">sd =</span> <span class="fl">0.2</span>,<span class="dt">sig.level =</span> <span class="fl">0.05</span>,<span class="dt">type =</span> <span class="st">&quot;one.sample&quot;</span> )</a></code></pre></div>
<pre><code>
     One-sample t test power calculation 

              n = 15.98026
          delta = 0.15
             sd = 0.2
      sig.level = 0.05
          power = 0.8
    alternative = two.sided</code></pre>
<p>The calculation shows that the study requires sixteen experimental units to have 80% power.</p>
</div>
</div>
</div>
<div id="power-of-two-sample-t-test" class="section level2">
<h2><span class="header-section-number">5.5</span> Power of two sample t test</h2>
<p>Statistical sample size calculations are calculated under the alternative hypothesis based on the type I error rate <span class="math inline">\(\alpha\)</span> and power <span class="math inline">\(1 - \beta\)</span>. In other words, we assume that the alternative hypothesis is true! Specifying the alternative hypothesis is usually tantamount to specifying a difference between the two groups that will be scientifically or practically meaningful. If two web pages are being tested to see which leads to higher sales is a 2% increase in sales worth the cost of redesigning the web site? If two drugs are being compared in a phase III clinical trial is a 5% difference in mortality rates clinically meaningful?</p>
<p>Sample size estimation not only depends on the effect size [<em>the clinically meaningful difference is often called an effect size</em>], but also on the variance. The larger the variance, the harder it is to detect the difference and thus a larger sample size is needed.</p>
<p>To fix idea let’s suppose that a phase III clinical trials is being designed and a continuous outcome <span class="math inline">\(Y\)</span> is the primary outcome. Although, the methods below are valid for experimental contexts beyond clinical trials.</p>
<p>Consider a two-sample comparison with continuous outcomes. Let <span class="math inline">\(Y_{ik}\)</span> be the observed outcome for the <span class="math inline">\(i^{th}\)</span> subject in the <span class="math inline">\(kth\)</span> treatment group, for <span class="math inline">\(i = 1,...,n_k\)</span>, and <span class="math inline">\(k= 1,2\)</span>. The outcomes in the two groups are assumed to be independent and normally distributed with different means but an equal variance <span class="math inline">\(\sigma^2\)</span>,</p>
<p><span class="math display">\[Y_{ik} \sim N(\mu_k,\sigma^2).\]</span></p>
<p>Let <span class="math inline">\(\theta=\mu_1-\mu_2\)</span>, the difference in the mean between treatment 1 (the new therapy) and treatment 2 (the standard of care).
To test whether the effects of the two treatments are the same, we formulate the null and alternative hypotheses as <span class="math inline">\(H_0:\theta =0\)</span> versus <span class="math inline">\(H_1:\theta \ne 0.\)</span></p>
<p>The two-sample t-statistic <span class="math inline">\(T_n\)</span> discriminates between <span class="math inline">\(H_0\)</span> and <span class="math inline">\(H_1\)</span>. The p-value is calculated by gauging the observed value of <span class="math inline">\(T_n\)</span> against its distribution under <span class="math inline">\(H_0\)</span>. The hypothesis testing procedure assesses the strength of evidence contained in the data against the null hypothesis. If the p-value is adequately small, say, less than 0.05 under a two-sided test, we reject the null hypothesis and claim that there is a significant difference between the two treatments; otherwise there is no significant difference and the study is inconclusive.</p>
<p>The sample mean for each group is given by <span class="math inline">\({\bar Y}_k = (1/n_k)\sum_{i = 1}^{n_k} Y_{ik}\)</span>, <span class="math inline">\(k = 1,2\)</span>, and the pooled sample variance is</p>
<p><span class="math display">\[S^2_p= \frac{1}{n_1+n_2-2} \sum_{k = 1}^2 \sum_{i = 1}^{n_k} (Y_{ik}-{\bar Y}_k)^2.\]</span></p>
<p>Then the two-sample t statistic is given by</p>
<p><span class="math display">\[ T_n=\frac {{\bar Y}_1 - {\bar Y}_2}{S_p \sqrt{(1/n_1+1/n_2)}} \sim t_{n_1+n_2-2}.\]</span></p>
<p><span class="math inline">\(T_n \sim t_{n_1+n_2-2}\)</span> under <span class="math inline">\(H_0\)</span> and <span class="math inline">\(t_{n_1+n_2-2,\gamma}\)</span> with non-centrality parameter</p>
<p><span class="math display">\[ \gamma = \frac {\theta}{\sigma\sqrt{1/n_1+1/n_2}},\]</span></p>
<p>under <span class="math inline">\(H_1\)</span>.</p>
<p><span class="math inline">\(H_0\)</span> is rejected if <span class="math inline">\(\left| T_n \right| \ge t_{n_1+n_2-2,\alpha/2}\)</span> where <span class="math inline">\(t_{df,\alpha/2}\)</span> is the <span class="math inline">\(100(1-\alpha/2)th\)</span> percentile of the central t distribution with <span class="math inline">\(df\)</span> degrees of freedom.</p>
<p>The sample size can be determined by specifying the type I and type II error rates, the standard deviation, and the difference in treatment means that the clinical trial aims to detect.</p>
<p>The power of the test is</p>
<p><span class="math display">\[1-\beta = P(t_{n_1+n_2-2, \gamma} \ge t_{n_1+n_2-2, \alpha/2})+P(t_{n_1+n_2-2, \gamma} &lt; -t_{n_1+n_2-2, \alpha/2})\]</span></p>
<p>The sample size can be solved from this equation which does not have a closed form (see <span class="citation">Yin (<a href="#ref-yin2013clinical" role="doc-biblioref">2013</a>)</span>).</p>
<div id="calculating-the-power-of-the-two-sample-t-test-using-r" class="section level3">
<h3><span class="header-section-number">5.5.1</span> Calculating the Power of the Two Sample t-test using R</h3>
<div id="write-a-custom-function-to-calculate-power-1" class="section level4">
<h4><span class="header-section-number">5.5.1.1</span> Write a Custom Function to Calculate Power</h4>
<p>This can be programmed in R.</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb147-1" title="1">twosampttestpow &lt;-<span class="st"> </span><span class="cf">function</span>(alpha,n1,n2, mu1, mu2,sigma){</a>
<a class="sourceLine" id="cb147-2" title="2">delta &lt;-<span class="st"> </span>mu1<span class="op">-</span>mu2</a>
<a class="sourceLine" id="cb147-3" title="3">t.crit &lt;-<span class="kw">qt</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>,n1<span class="op">+</span>n2<span class="dv">-2</span>)</a>
<a class="sourceLine" id="cb147-4" title="4">t.gamma &lt;-<span class="st"> </span>delta<span class="op">/</span>(sigma<span class="op">*</span><span class="kw">sqrt</span>(<span class="dv">1</span><span class="op">/</span>n1<span class="op">+</span><span class="dv">1</span><span class="op">/</span>n2))</a>
<a class="sourceLine" id="cb147-5" title="5">t.power &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">pt</span>(t.crit,n1<span class="op">+</span>n2<span class="dv">-2</span>,<span class="dt">ncp =</span> t.gamma)<span class="op">+</span><span class="kw">pt</span>(<span class="op">-</span>t.crit,n1<span class="op">+</span>n2<span class="dv">-2</span>,<span class="dt">ncp =</span> t.gamma)</a>
<a class="sourceLine" id="cb147-6" title="6"><span class="kw">return</span>(t.power)</a>
<a class="sourceLine" id="cb147-7" title="7">}</a></code></pre></div>
<p>The power of a clinical trial to detect <span class="math inline">\(\theta = 1\)</span> with <span class="math inline">\(\sigma = 3,n_1 = n_2 = 50\)</span> is</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1"><span class="kw">twosampttestpow</span>(.<span class="dv">05</span>,<span class="dv">50</span>,<span class="dv">50</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)</a></code></pre></div>
<pre><code>[1] 0.3785749</code></pre>
</div>
<div id="use-power.t.test-to-calculate-power-1" class="section level4">
<h4><span class="header-section-number">5.5.1.2</span> Use <code>power.t.test()</code> to Calculate Power</h4>
<p>The built-in function <code>power.t.test()</code> can also be used and gives the same results.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" title="1"><span class="kw">power.t.test</span>(<span class="dt">n =</span> <span class="dv">50</span>,<span class="dt">delta =</span> <span class="dv">1</span>,<span class="dt">sd =</span> <span class="dv">3</span>,<span class="dt">sig.level =</span> <span class="fl">0.05</span>)</a></code></pre></div>
<pre><code>
     Two-sample t test power calculation 

              n = 50
          delta = 1
             sd = 3
      sig.level = 0.05
          power = 0.3784221
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
<p>So the study would require 50 subjects per group to achieve 38% power to detect a difference of <span class="math inline">\(\theta = 1\)</span> at the 5% significance level assuming <span class="math inline">\(\sigma = 3\)</span>. <code>power.t.test()</code> can also output the number of subjects required to achieve a certain power. Suppose the investigators want to know how many subjects per group would have to be enrolled in each group to achieve 80% power under the same conditions?</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" title="1"><span class="kw">power.t.test</span>(<span class="dt">power =</span> <span class="fl">0.8</span>,<span class="dt">delta =</span> <span class="dv">1</span>,<span class="dt">sd =</span> <span class="dv">3</span>,<span class="dt">sig.level =</span> <span class="fl">0.05</span>)</a></code></pre></div>
<pre><code>
     Two-sample t test power calculation 

              n = 142.2466
          delta = 1
             sd = 3
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
<p>142 subjects would be required in each group to achieve 80% power.</p>
<p>The following plot shows power of the two-sample t-test as a function of the difference <span class="math inline">\(\theta\)</span> to be detected and equal sample size per group.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" title="1"><span class="co"># Study power as a function of theta and sample size</span></a>
<a class="sourceLine" id="cb154-2" title="2">pow &lt;-<span class="st"> </span><span class="kw">power.t.test</span>(<span class="dt">n =</span> <span class="dv">30</span>,<span class="dt">delta =</span> <span class="kw">seq</span>(<span class="fl">0.01</span>,<span class="dv">2</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dt">sd =</span> <span class="fl">1.5</span>,<span class="dt">power =</span> <span class="ot">NULL</span>,</a>
<a class="sourceLine" id="cb154-3" title="3">                    <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,<span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,<span class="dt">strict =</span> T)</a>
<a class="sourceLine" id="cb154-4" title="4"><span class="kw">plot</span>(pow<span class="op">$</span>delta,pow<span class="op">$</span>power,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">main =</span> <span class="st">&quot;Power of Two-Sample T-Test&quot;</span>,</a>
<a class="sourceLine" id="cb154-5" title="5">     <span class="dt">xlab =</span> <span class="st">&quot;theta&quot;</span>,<span class="dt">ylab =</span> <span class="st">&quot;Power&quot;</span>)</a>
<a class="sourceLine" id="cb154-6" title="6">pow &lt;-<span class="st"> </span><span class="kw">power.t.test</span>(<span class="dt">n =</span> <span class="dv">20</span>,<span class="dt">delta =</span> <span class="kw">seq</span>(<span class="fl">0.01</span>,<span class="dv">2</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dt">sd =</span> <span class="fl">1.5</span>,<span class="dt">power =</span> <span class="ot">NULL</span>,</a>
<a class="sourceLine" id="cb154-7" title="7">                    <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,<span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,<span class="dt">strict =</span> T)</a>
<a class="sourceLine" id="cb154-8" title="8"><span class="kw">points</span>(pow<span class="op">$</span>delta,pow<span class="op">$</span>power,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">lty =</span> <span class="dv">2</span>,<span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb154-9" title="9">pow &lt;-<span class="st"> </span><span class="kw">power.t.test</span>(<span class="dt">n =</span> <span class="dv">10</span>,<span class="dt">delta =</span> <span class="kw">seq</span>(<span class="fl">0.01</span>,<span class="dv">2</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dt">sd =</span> <span class="fl">1.5</span>,<span class="dt">power =</span> <span class="ot">NULL</span>,</a>
<a class="sourceLine" id="cb154-10" title="10">                    <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,<span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,<span class="dt">strict =</span> T)</a>
<a class="sourceLine" id="cb154-11" title="11"><span class="kw">points</span>(pow<span class="op">$</span>delta,pow<span class="op">$</span>power,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">lty =</span> <span class="dv">3</span>,<span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb154-12" title="12"><span class="kw">abline</span>(<span class="dt">a =</span> <span class="fl">0.8</span>,<span class="dt">b =</span> <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb154-13" title="13"><span class="kw">legend</span>(<span class="st">&quot;bottomright&quot;</span>,<span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;N = 30&quot;</span>,<span class="st">&quot;N = 20&quot;</span>,<span class="st">&quot;N = 10&quot;</span>),</a>
<a class="sourceLine" id="cb154-14" title="14">       <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>),<span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;red&quot;</span>))</a></code></pre></div>
<p><img src="04-powersampsize_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>This next plot shows power as a function of <span class="math inline">\(\sigma\)</span> and sample size per group.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb155-1" title="1"><span class="co"># Power as a funtion of sample size and sd</span></a>
<a class="sourceLine" id="cb155-2" title="2">pow &lt;-<span class="st"> </span><span class="kw">power.t.test</span>(<span class="dt">n =</span> <span class="dv">30</span>,<span class="dt">delta =</span> <span class="dv">1</span>,<span class="dt">sd =</span> <span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dt">power =</span> <span class="ot">NULL</span>,</a>
<a class="sourceLine" id="cb155-3" title="3">                    <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,<span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,<span class="dt">strict =</span> T)</a>
<a class="sourceLine" id="cb155-4" title="4"><span class="kw">plot</span>(pow<span class="op">$</span>sd,pow<span class="op">$</span>power,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">main =</span> <span class="st">&quot;Power of Two-Sample T-Test&quot;</span>,</a>
<a class="sourceLine" id="cb155-5" title="5">     <span class="dt">xlab =</span> <span class="st">&quot;SD&quot;</span>,<span class="dt">ylab =</span> <span class="st">&quot;Power&quot;</span>)</a>
<a class="sourceLine" id="cb155-6" title="6">pow &lt;-<span class="st"> </span><span class="kw">power.t.test</span>(<span class="dt">n =</span> <span class="dv">20</span>,<span class="dt">delta =</span> <span class="dv">1</span>,<span class="dt">sd =</span> <span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dt">power =</span> <span class="ot">NULL</span>,</a>
<a class="sourceLine" id="cb155-7" title="7">                    <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,<span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,<span class="dt">strict =</span> T)</a>
<a class="sourceLine" id="cb155-8" title="8"><span class="kw">points</span>(pow<span class="op">$</span>sd,pow<span class="op">$</span>power,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">lty =</span> <span class="dv">2</span>,<span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>)</a>
<a class="sourceLine" id="cb155-9" title="9">pow &lt;-<span class="st"> </span><span class="kw">power.t.test</span>(<span class="dt">n =</span> <span class="dv">10</span>,<span class="dt">delta =</span> <span class="dv">1</span>,<span class="dt">sd =</span> <span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dt">power =</span> <span class="ot">NULL</span>,</a>
<a class="sourceLine" id="cb155-10" title="10">                    <span class="dt">type =</span> <span class="st">&quot;two.sample&quot;</span>,<span class="dt">alternative =</span> <span class="st">&quot;two.sided&quot;</span>,<span class="dt">strict =</span> T)</a>
<a class="sourceLine" id="cb155-11" title="11"><span class="kw">points</span>(pow<span class="op">$</span>sd,pow<span class="op">$</span>power,<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">lty =</span> <span class="dv">3</span>,<span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)</a>
<a class="sourceLine" id="cb155-12" title="12"><span class="kw">abline</span>(<span class="dt">a =</span> <span class="fl">0.8</span>,<span class="dt">b =</span> <span class="dv">0</span>)</a>
<a class="sourceLine" id="cb155-13" title="13"><span class="kw">legend</span>(<span class="st">&quot;topright&quot;</span>,<span class="dt">legend =</span> <span class="kw">c</span>(<span class="st">&quot;N = 30&quot;</span>,<span class="st">&quot;N = 20&quot;</span>,<span class="st">&quot;N = 10&quot;</span>),</a>
<a class="sourceLine" id="cb155-14" title="14">       <span class="dt">lty =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>),<span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;black&quot;</span>,<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;red&quot;</span>))</a></code></pre></div>
<p><img src="04-powersampsize_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="effect-size" class="section level2">
<h2><span class="header-section-number">5.6</span> Effect size</h2>
<p>In some studies instead of specifying the difference in treatment means and standard deviation separately the ratio</p>
<p><span class="math display">\[\frac{\mu_1-\mu_2}{\sigma}\]</span></p>
<p>can be specified. This ratio is called the scaled effect size. <span class="citation">Cohen (<a href="#ref-cohen1992power" role="doc-biblioref">1992</a>)</span> suggests that effect sizes of 0.2, 0.5, 0.8 correspond to small, medium , and large effects. Cohen (1992) states that:</p>
<blockquote>
<p>Researchers find specifying the ES the most difficult part of power analysis … To convey the meaning of any given ES index, it is necessary to have some idea of its scale … My intent was that medium ES represent an effect likely to be visible to the naked eye of a careful observer, (it has since been noted in effect- size surveys that it approximates the average size of observed effects in various fields.) I set small ES to be noticeably smaller than medium but not so small as to be trivial, and I set large ES to be the same distance above medium as small was below it. Although the definitions were made subjectively …</p>
</blockquote>
<p>Power as a function of effect size can be investigated using R.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1">pow.t &lt;-<span class="st"> </span><span class="cf">function</span>(theta){</a>
<a class="sourceLine" id="cb156-2" title="2">  alpha &lt;-<span class="fl">0.05</span></a>
<a class="sourceLine" id="cb156-3" title="3">  nA &lt;-<span class="st"> </span><span class="dv">10</span></a>
<a class="sourceLine" id="cb156-4" title="4">  nB &lt;-<span class="st"> </span><span class="dv">10</span></a>
<a class="sourceLine" id="cb156-5" title="5">  t.crit &lt;-<span class="kw">qt</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>,nA<span class="op">+</span>nB<span class="dv">-2</span>)</a>
<a class="sourceLine" id="cb156-6" title="6">  t.gamma &lt;-<span class="st"> </span>theta<span class="op">/</span>(<span class="kw">sqrt</span>(<span class="dv">1</span><span class="op">/</span>nA<span class="op">+</span><span class="dv">1</span><span class="op">/</span>nB))</a>
<a class="sourceLine" id="cb156-7" title="7">  t.power &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">pt</span>(t.crit,nA<span class="op">+</span>nB<span class="dv">-2</span>,<span class="dt">ncp =</span> t.gamma)<span class="op">+</span><span class="kw">pt</span>(<span class="op">-</span>t.crit,nA<span class="op">+</span>nB<span class="dv">-2</span>,<span class="dt">ncp =</span> t.gamma)</a>
<a class="sourceLine" id="cb156-8" title="8">  <span class="kw">return</span>(t.power)</a>
<a class="sourceLine" id="cb156-9" title="9">}</a>
<a class="sourceLine" id="cb156-10" title="10"></a>
<a class="sourceLine" id="cb156-11" title="11">x &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="op">-</span><span class="dv">3</span>,<span class="dv">3</span>,<span class="dt">by =</span> <span class="fl">0.1</span>)</a>
<a class="sourceLine" id="cb156-12" title="12"><span class="kw">plot</span>(x,<span class="kw">pow.t</span>(x),<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,<span class="dt">xlab=</span><span class="st">&quot;&quot;</span>,<span class="dt">ylab =</span> <span class="st">&quot;power&quot;</span>,<span class="dt">main =</span> <span class="st">&quot;Two-Sample T-Test Power and Effect Size, N = 10&quot;</span>)</a>
<a class="sourceLine" id="cb156-13" title="13"><span class="kw">abline</span>(<span class="dt">v=</span><span class="op">+</span><span class="fl">1.33</span>,<span class="dt">lty =</span> <span class="dv">2</span>,<span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)  </a>
<a class="sourceLine" id="cb156-14" title="14"><span class="kw">abline</span>(<span class="dt">v=</span><span class="op">-</span><span class="fl">1.33</span>,<span class="dt">lty =</span> <span class="dv">2</span>,<span class="dt">col =</span> <span class="st">&quot;red&quot;</span>)  </a>
<a class="sourceLine" id="cb156-15" title="15"><span class="kw">abline</span>(<span class="dt">h =</span> <span class="fl">0.8</span>,<span class="dt">lty =</span> <span class="dv">2</span>,<span class="dt">col =</span> <span class="st">&quot;blue&quot;</span>) </a></code></pre></div>
<p><img src="04-powersampsize_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>The plot shows that for <span class="math inline">\(n_1 = n_2 = 10\)</span> the two-sample t-test has at least 80% power for detecting effect sizes that are at least 1.3.</p>
</div>
<div id="sample-size---known-variance-and-equal-allocation" class="section level2">
<h2><span class="header-section-number">5.7</span> Sample size - known variance and equal allocation</h2>
<p>Consider a study where experimental units are randomized into two treatment groups and the investigator would like an equal number of experimental units in each group.</p>
<p>If the variance is known then the test statistic is</p>
<p><span class="math display">\[ Z=\frac {{\bar Y}_1 - {\bar Y}_2}{\sigma \sqrt{(1/n_1+1/n_2)}} \sim N(0,1).\]</span></p>
<p>This is the known as the two-sample z-test.</p>
<p>The power at <span class="math inline">\(\theta=\theta_1\)</span> is given by</p>
<p><span class="math display">\[1-\beta= P\left( Z \ge z_{\alpha/2} - \frac{\theta_1}{\sigma \sqrt{1/n_1+1/n_2}}  \right) + P\left( Z &lt; -z_{\alpha/2} - \frac{\theta_1}{\sigma \sqrt{1/n_1+1/n_2}}  \right).\]</span></p>
<p>Ignoring terms smaller than <span class="math inline">\(\alpha/2\)</span> and combining positive and negative <span class="math inline">\(\theta\)</span></p>
<p><span class="math display">\[\beta \approx \Phi\left( z_{\alpha/2} - \frac{\left|\theta_1\right|}{\sigma \sqrt{1/n_1+1/n_2}} \right).\]</span></p>
<p>The sample size is obtained by solving</p>
<p><span class="math display">\[z_{\beta}+z_{\alpha/2} = \left( \frac{\left|\theta_1\right|}{\sigma \sqrt{1/n_1+1/n_2}} \right).\]</span></p>
<p>If we assume that there will be an equal allocation of subjects to each group then <span class="math inline">\(n_1 = n_2 = n/2\)</span>, the total sample size is</p>
<p><span class="math display">\[ n= \frac {4\sigma^2 \left(z_{\beta}+z_{\alpha/2}\right)^2}{\theta^2}.\]</span></p>
</div>
<div id="sample-size---known-variance-and-unequal-allocation" class="section level2">
<h2><span class="header-section-number">5.8</span> Sample size - known variance and unequal allocation</h2>
<p>In many studies comparing two treatments it is desirable to put more experimental units into the experimental group to learn more about this treatment. In a phase III clinical trial if the patient allocation between the two groups is <span class="math inline">\(r = n_1/n_2\)</span> then <span class="math inline">\(n_1 = r\cdot n_2\)</span> and</p>
<p><span class="math display">\[ n_2=\frac {(1+1/r)\sigma^2 \left(z_{\beta}+z_{\alpha/2}\right)^2} {\theta^2}.\]</span></p>
<p>An R function to compute the sample size in groups 1 and 2 for unequal allocation is</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb157-1" title="1">size2z.uneq.test &lt;-<span class="st"> </span><span class="cf">function</span>(theta,alpha,beta,sigma,r)</a>
<a class="sourceLine" id="cb157-2" title="2">{</a>
<a class="sourceLine" id="cb157-3" title="3">  zalpha &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb157-4" title="4">  zbeta &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>beta)</a>
<a class="sourceLine" id="cb157-5" title="5">  n2 &lt;-<span class="st"> </span>(<span class="dv">1</span><span class="op">+</span><span class="dv">1</span><span class="op">/</span>r)<span class="op">*</span>(sigma<span class="op">*</span>(zalpha<span class="op">+</span>zbeta)<span class="op">/</span>theta)<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb157-6" title="6">  n1 &lt;-<span class="st"> </span>r<span class="op">*</span>n2</a>
<a class="sourceLine" id="cb157-7" title="7">  <span class="kw">return</span>(<span class="kw">c</span>(n1,n2))</a>
<a class="sourceLine" id="cb157-8" title="8">}</a></code></pre></div>
<p>The sample size required for 90% power to detect <span class="math inline">\(\theta = 1\)</span> with <span class="math inline">\(\sigma = 2\)</span> at the 5% level in a trial where two patients will be enrolled in the experimental arm for every patient enrolled in the control arm is 126 in the control group and 63 in the experimental group. The total sample size is 189.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" title="1"><span class="co"># sample size for theta =1, alpha = 0.05, beta = 0.1, sigma = 2, r = 2</span></a>
<a class="sourceLine" id="cb158-2" title="2"><span class="kw">size2z.uneq.test</span>(<span class="dv">1</span>,.<span class="dv">05</span>,.<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>)[<span class="dv">1</span>] <span class="co"># group 1 sample size (experimental group)</span></a></code></pre></div>
<pre><code>[1] 126.0891</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" title="1"><span class="kw">size2z.uneq.test</span>(<span class="dv">1</span>,.<span class="dv">05</span>,.<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>)[<span class="dv">2</span>] <span class="co"># group 2 sample size (control group)</span></a></code></pre></div>
<pre><code>[1] 63.04454</code></pre>
<p>The power of the two-sample z-test can be studied as a function of the allocation ratio <span class="math inline">\(r\)</span>.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb162-1" title="1"><span class="co"># power of z test as a function of allocation ratio r,</span></a>
<a class="sourceLine" id="cb162-2" title="2"><span class="co"># total sample size n, alpha, theta, and sigma</span></a>
<a class="sourceLine" id="cb162-3" title="3">pow.z.test &lt;-<span class="st"> </span><span class="cf">function</span>(r,n,alpha,theta,sigma)</a>
<a class="sourceLine" id="cb162-4" title="4">{</a>
<a class="sourceLine" id="cb162-5" title="5">  n2 &lt;-<span class="st"> </span>n<span class="op">/</span>(r<span class="op">+</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb162-6" title="6">  x &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>)<span class="op">-</span><span class="kw">abs</span>(theta)<span class="op">/</span>(sigma<span class="op">*</span><span class="kw">sqrt</span>(<span class="dv">1</span><span class="op">/</span>(r<span class="op">*</span>n2)<span class="op">+</span><span class="dv">1</span><span class="op">/</span>n2))</a>
<a class="sourceLine" id="cb162-7" title="7">  pow &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(x)</a>
<a class="sourceLine" id="cb162-8" title="8">  <span class="kw">return</span>(pow)</a>
<a class="sourceLine" id="cb162-9" title="9">}</a>
<a class="sourceLine" id="cb162-10" title="10"></a>
<a class="sourceLine" id="cb162-11" title="11"><span class="kw">plot</span>(<span class="dt">x =</span> <span class="kw">seq</span>(.<span class="dv">1</span>,<span class="dv">5</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dt">y =</span> <span class="kw">pow.z.test</span>(<span class="kw">seq</span>(.<span class="dv">1</span>,<span class="dv">5</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dv">168</span>,.<span class="dv">05</span>,<span class="dv">1</span>,<span class="dv">2</span>),<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,</a>
<a class="sourceLine" id="cb162-12" title="12">     <span class="dt">xlab =</span> <span class="st">&quot;Allocation ratio&quot;</span>,<span class="dt">ylab =</span> <span class="st">&quot;Power&quot;</span>,</a>
<a class="sourceLine" id="cb162-13" title="13">     <span class="dt">main =</span> <span class="st">&quot;Power vs. allocation ratio with total sample size fixed at </span><span class="ch">\n</span><span class="st"> n = 168 alpha = 0.05&quot;</span>) </a></code></pre></div>
<p><img src="04-powersampsize_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>The plot shows that imbalance typically leads to loss of power.</p>
</div>
<div id="comparing-proportions-for-binary-outcomes" class="section level2">
<h2><span class="header-section-number">5.9</span> Comparing Proportions for Binary Outcomes</h2>
<p>In this section we will consider studies where the primary endpoint is dichotomous. In a clinical trial the outcome could be whether a patient has responded to the treatment, or whether a patient has experienced toxicity. More specifically, consider a phase III clinical trial where patients are randomized to two groups and a binary outcome is measured as the outcome.</p>
<p>Let <span class="math inline">\(p_1\)</span> denote the response rate of the experimental drug, <span class="math inline">\(p_2\)</span> as that of the standard drug, and the difference is <span class="math inline">\(\theta= p_1—p_2\)</span>. Let <span class="math inline">\(Y_{ik}\)</span> be the binary outcome for subject <span class="math inline">\(i\)</span> in arm <span class="math inline">\(k\)</span>; that is,</p>
<p><span class="math display">\[Y_{ik} = \left\{
    \begin{array}{ll}
        1  &amp; \mbox{with probability } p_k \\
        0 &amp; \mbox{with probability } 1-p_k,
    \end{array}
\right.\]</span></p>
<p>for <span class="math inline">\(i = 1,...,n_k\)</span> and <span class="math inline">\(k = 1,2\)</span>. The sum of independent and identically distributed Bernoulli random variables has a binomial distribution,</p>
<p><span class="math display">\[ \sum_{i = 1}^{n_k} Y_{ik} \sim Bin(n_k,p_k), \thinspace k = 1,2.\]</span></p>
<p>(see <span class="citation">Yin (<a href="#ref-yin2013clinical" role="doc-biblioref">2013</a>)</span>, pg. 173-174)</p>
<p>The sample proportion for group <span class="math inline">\(k\)</span> is</p>
<p><span class="math display">\[{\hat p}_k={\bar Y}_k = (1/n_k)\sum_{i = 1}^{n_k} Y_{ik}, \thinspace k = 1,2,\]</span></p>
<p>and <span class="math inline">\(E\left( {\bar Y}_k\right)=p_k\)</span> and <span class="math inline">\(Var\left({\bar Y}_k \right)=\frac{p_k(1-p_k)}{n_k}\)</span>.</p>
<p>The goal of the clinical trial is to determine if there is a difference between the two groups using a binary endpoint. That is we want to test <span class="math inline">\(H_0: \theta = 0\)</span> versus <span class="math inline">\(H_1: \theta \ne 0.\)</span></p>
<p>The test statistic (assuming that <span class="math inline">\(H_0\)</span> is true) is:</p>
<p><span class="math display">\[T = \frac {{\hat p}_1-{\hat p}_2} {\sqrt{p_1(1-p_1)/n_1+p_2(1-p_2)/n_2}} \sim N(0,1),\]</span></p>
<p>The test rejects at level <span class="math inline">\(\alpha\)</span> if and only if</p>
<p><span class="math display">\[\left|T\right| \ge z_{\alpha/2}.\]</span></p>
<p>Using the same argument as the case with continuous endpoints and ignoring terms smaller than <span class="math inline">\(\alpha/2\)</span> we can solve for <span class="math inline">\(\beta\)</span></p>
<p><span class="math display">\[\beta \approx \Phi\left( z_{\alpha/2}- \frac{|\theta_1|}{\sqrt{p_1(1-p_1)/n_1+p_2(1-p_2)/n_2}}   \right).\]</span></p>
<p>Using this formula to solve for sample size. If <span class="math inline">\(n_1 = r \cdot n_2\)</span> then</p>
<p><span class="math display">\[n_2= \frac {\left(z_{\alpha/2}+z_{\beta}\right)^2}{\theta^2} \left(p_1(1-p_1)/r+p_2(1-p_2) \right). \]</span></p>
<p>The built-in R function <code>power.prop.test()</code> can be used to calculate sample size or power. For example suppose that the standard treatment for a disease has a response rate of 20%, and an experimental treatment is anticipated to have a response rate of 28%. The researchers want both arms to have an equal number of subjects. How many patients should be enrolled if the study will conduct a two-sided test at the 5% level with 80% power?</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1"><span class="kw">power.prop.test</span>(<span class="dt">p1 =</span> <span class="fl">0.2</span>,<span class="dt">p2 =</span> <span class="fl">0.25</span>,<span class="dt">power =</span> <span class="fl">0.8</span>)</a></code></pre></div>
<pre><code>
     Two-sample comparison of proportions power calculation 

              n = 1093.739
             p1 = 0.2
             p2 = 0.25
      sig.level = 0.05
          power = 0.8
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
<p>This means that 1094 should be enrolled in each group.</p>
</div>
<div id="calculating-power-by-simulation" class="section level2">
<h2><span class="header-section-number">5.10</span> Calculating Power by simulation</h2>
<p>If the test statistic and distribution of the test statistic are known then the power of the test can be calculated via simulation.</p>
<p>Consider a two-sample t-test with 30 subjects per group and the standard deviation of the clinical outcome is known to be 1. What is the power of the test <span class="math inline">\(H_0:\mu_1-\mu_2 = 0\)</span> versus <span class="math inline">\(H_1:\mu_1-\mu_2 = 0.5\)</span>, at the 5% significance level?</p>
<p>The power is the proportion of times that the test correctly rejects the null hypothesis in repeated sampling.</p>
<p>We can simulate a single study using the <code>rnorm()</code> command. Let’s assume that <span class="math inline">\(n_1 = n_2 = 30, \mu_1 = 3.5, \mu_2 = 3, \sigma = 1, \alpha = 0.05\)</span>.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" title="1"><span class="kw">set.seed</span>(<span class="dv">2301</span>)</a>
<a class="sourceLine" id="cb165-2" title="2"><span class="co"># simulate 1 study with two samples with 30 observations: one sample is N(3.5,1) </span></a>
<a class="sourceLine" id="cb165-3" title="3"><span class="co"># the other is N(3,1) then do a two-sample t-test on each study </span></a>
<a class="sourceLine" id="cb165-4" title="4"><span class="kw">t.test</span>(<span class="kw">rnorm</span>(<span class="dv">30</span>,<span class="dt">mean =</span> <span class="fl">3.5</span>,<span class="dt">sd =</span> <span class="dv">1</span>),<span class="kw">rnorm</span>(<span class="dv">30</span>,<span class="dt">mean =</span> <span class="dv">3</span>,<span class="dt">sd =</span> <span class="dv">1</span>),<span class="dt">var.equal =</span> T)</a></code></pre></div>
<pre><code>
    Two Sample t-test

data:  rnorm(30, mean = 3.5, sd = 1) and rnorm(30, mean = 3, sd = 1)
t = 2.1462, df = 58, p-value = 0.03605
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 0.03458122 0.99248595
sample estimates:
mean of x mean of y 
 3.339362  2.825828 </code></pre>
<p>We would reject the null hypothesis at the 5% level since the p-value is 0.0360489.</p>
<p>Suppose that 10 studies are simulated. What proportion of these 10 studies will reject the null hypothesis at the 5% level? To investigate how many times the two-sample t-test will reject at the 5% level the <code>replicate()</code> command will be used to generate 10 studies and calculate the p-value in each study. It will still be assumed that <span class="math inline">\(n_1 = n_2 = 30, \mu_1 = 3.5, \mu_2 = 3, \sigma = 1, \alpha = 0.05\)</span>.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" title="1"><span class="kw">set.seed</span>(<span class="dv">2301</span>) </a>
<a class="sourceLine" id="cb167-2" title="2"><span class="co"># simulate 10 studies with two samples with 30 observations: one sample is N(3.5,1) </span></a>
<a class="sourceLine" id="cb167-3" title="3"><span class="co"># the other is N(3,1) then do a two-sample t-test on each study </span></a>
<a class="sourceLine" id="cb167-4" title="4">pvals &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">10</span>,<span class="kw">t.test</span>(<span class="kw">rnorm</span>(<span class="dv">30</span>,<span class="dt">mean =</span> <span class="fl">3.5</span>,<span class="dt">sd =</span> <span class="dv">1</span>),<span class="kw">rnorm</span>(<span class="dv">30</span>,<span class="dt">mean =</span> <span class="dv">3</span>,<span class="dt">sd =</span> <span class="dv">1</span>),</a>
<a class="sourceLine" id="cb167-5" title="5">                             <span class="dt">var.equal =</span> T)<span class="op">$</span>p.value)</a>
<a class="sourceLine" id="cb167-6" title="6">pvals <span class="co"># print out 10 p-values</span></a></code></pre></div>
<pre><code> [1] 0.03604893 0.15477655 0.01777959 0.40851999 0.34580930 0.11131007
 [7] 0.14788381 0.00317709 0.09452230 0.39173723</code></pre>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" title="1"><span class="kw">sum</span>(pvals<span class="op">&lt;=</span><span class="fl">0.05</span>)<span class="op">/</span><span class="dv">10</span> <span class="co">#power is the number of times the test rejects at the 5% level</span></a></code></pre></div>
<pre><code>[1] 0.3</code></pre>
<p>But, since we only simulated 10 studies the estimate of power will have a large standard error. So let’s try simulating 10,000 studies so that we can obtain a more precise estimate of power.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" title="1"><span class="kw">set.seed</span>(<span class="dv">2301</span>)</a>
<a class="sourceLine" id="cb171-2" title="2">pvals &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">10000</span>,<span class="kw">t.test</span>(<span class="kw">rnorm</span>(<span class="dv">30</span>,<span class="dt">mean =</span> <span class="fl">3.5</span>,<span class="dt">sd =</span> <span class="dv">1</span>),<span class="kw">rnorm</span>(<span class="dv">30</span>,<span class="dt">mean =</span> <span class="dv">3</span>,<span class="dt">sd =</span> <span class="dv">1</span>),</a>
<a class="sourceLine" id="cb171-3" title="3">                             <span class="dt">var.equal =</span> T)<span class="op">$</span>p.value)</a>
<a class="sourceLine" id="cb171-4" title="4"><span class="kw">sum</span>(pvals<span class="op">&lt;=</span><span class="fl">0.05</span>)<span class="op">/</span><span class="dv">10000</span> </a></code></pre></div>
<pre><code>[1] 0.4881</code></pre>
<p>This is much closer to the theoretical power obtained from <code>power.t.test()</code>.</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" title="1"><span class="kw">power.t.test</span>(<span class="dt">n =</span> <span class="dv">30</span>,<span class="dt">delta =</span> <span class="fl">0.5</span>,<span class="dt">sd =</span> <span class="dv">1</span>,<span class="dt">sig.level =</span> <span class="fl">0.05</span>)</a></code></pre></div>
<pre><code>
     Two-sample t test power calculation 

              n = 30
          delta = 0.5
             sd = 1
      sig.level = 0.05
          power = 0.477841
    alternative = two.sided

NOTE: n is number in *each* group</code></pre>
<p>The built-in R functions <code>power.t.test()</code> and <code>power.prop.test()</code> don’t have an option for calculating power where the there is unequal allocation of subjects between groups. One option is to simulate power for the scenarios that are of interest. Another option is to write your own function using the formula derived above.</p>
<p>In the previous example the standard treatment for a disease has a response rate of 20%, and an experimental treatment is anticipated to have a response rate of 28%. The researchers want both arms to have an equal number of subjects. The power calculation above revealed that the study will require 1094 patients for 80% power. What would happen to the power if the researchers put 1500 patients in the experimental arm and 500 patients in the control arm?</p>
<p>The number of subjects in the experimental arm that have a positive response to treatment will be an observation from a <span class="math inline">\(Bin(1500,0.28)\)</span> and the number of subjects that have a positive response to the standard treatment will be an observation from a <span class="math inline">\(Bin(500,0.2)\)</span>. We can obtain simulated responses from these distributions using the <code>rbinom()</code> command in R.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1"><span class="kw">set.seed</span>(<span class="dv">2301</span>)</a>
<a class="sourceLine" id="cb175-2" title="2"><span class="kw">rbinom</span>(<span class="dv">1</span>,<span class="dv">1500</span>,<span class="fl">0.28</span>)</a></code></pre></div>
<pre><code>[1] 403</code></pre>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb177-1" title="1"><span class="kw">rbinom</span>(<span class="dv">1</span>,<span class="dv">500</span>,<span class="fl">0.20</span>)</a></code></pre></div>
<pre><code>[1] 89</code></pre>
<p>In this simulated clinical trial 431 of the 1500 patients in the experimental arm had a positive response to the experimental treatment and 101 of the 500 patients in the control arm had a positive response to the standard treatment. The p-value for this simulated study can be obtained using <code>prop.test()</code>.</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" title="1"><span class="kw">set.seed</span>(<span class="dv">2301</span>)</a>
<a class="sourceLine" id="cb179-2" title="2"><span class="kw">prop.test</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="kw">rbinom</span>(<span class="dv">1</span>,<span class="dv">1500</span>,<span class="fl">0.28</span>),<span class="kw">rbinom</span>(<span class="dv">1</span>,<span class="dv">500</span>,<span class="fl">0.20</span>)),<span class="dt">n =</span> <span class="kw">c</span>(<span class="dv">1500</span>,<span class="dv">500</span>),<span class="dt">correct =</span> F)</a></code></pre></div>
<pre><code>
    2-sample test for equality of proportions without continuity
    correction

data:  c(rbinom(1, 1500, 0.28), rbinom(1, 500, 0.2)) out of c(1500, 500)
X-squared = 16.62, df = 1, p-value = 4.568e-05
alternative hypothesis: two.sided
95 percent confidence interval:
 0.05032654 0.13100680
sample estimates:
   prop 1    prop 2 
0.2686667 0.1780000 </code></pre>
<p>In this study the p-value is 0, which is less than 0.05 so there would be evidence that the new treatment is significantly better than the standard treatment. A power simulation repeats this process a large number of times. The <code>repeat()</code> command can be used for the repetition. In the example below we simulate 10,000 hypothetical studies to calculate power.</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" title="1"><span class="kw">set.seed</span>(<span class="dv">2301</span>)</a>
<a class="sourceLine" id="cb181-2" title="2">pvals &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">10000</span>,<span class="kw">prop.test</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="kw">rbinom</span>(<span class="dt">n =</span> <span class="dv">1</span>,<span class="dt">size =</span> <span class="dv">1500</span>,<span class="dt">prob =</span> <span class="fl">0.25</span>),<span class="kw">rbinom</span>(<span class="dt">n =</span> <span class="dv">1</span>,<span class="dt">size =</span> <span class="dv">500</span>,<span class="dt">prob =</span> <span class="fl">0.20</span>)),<span class="dt">n =</span> <span class="kw">c</span>(<span class="dv">1500</span>,<span class="dv">500</span>),<span class="dt">correct =</span> F)<span class="op">$</span>p.value)</a>
<a class="sourceLine" id="cb181-3" title="3"><span class="kw">sum</span>(pvals<span class="op">&lt;=</span><span class="fl">0.05</span>)<span class="op">/</span><span class="dv">10000</span></a></code></pre></div>
<pre><code>[1] 0.6231</code></pre>
<p>If the researchers decide to have a 3:1 allocation ratio of patients in the treatment to control arm then the power will decrease to approximately 62%.</p>
</div>
<div id="questions-2" class="section level2">
<h2><span class="header-section-number">5.11</span> Questions</h2>
<ol style="list-style-type: decimal">
<li>The R function</li>
</ol>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1"><span class="co"># sample size for two-sample Z test equal allocation</span></a>
<a class="sourceLine" id="cb183-2" title="2">size2z.test &lt;-<span class="st"> </span><span class="cf">function</span>(theta,alpha,beta,sigma)</a>
<a class="sourceLine" id="cb183-3" title="3">{</a>
<a class="sourceLine" id="cb183-4" title="4">  zalpha &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb183-5" title="5">  zbeta &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>beta)</a>
<a class="sourceLine" id="cb183-6" title="6">  (<span class="dv">2</span><span class="op">*</span>sigma<span class="op">*</span>(zalpha<span class="op">+</span>zbeta)<span class="op">/</span>theta)<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb183-7" title="7">}</a></code></pre></div>
<p>implements the sample size formula for calculating the sample size for a test of <span class="math inline">\(H_0:\theta = 0\)</span> versus <span class="math inline">\(H_1:\theta \ne 0\)</span>, where <span class="math inline">\(\theta=\mu_1-\mu_2\)</span>.</p>
<p><span class="math display">\[n=\left(\frac{2\sigma\left(z_{\alpha/2}+z_{\beta}\right)}{\theta}\right)^2\]</span></p>
<ol style="list-style-type: lower-alpha">
<li>What are the main assumptions behind this sample size formula? (see lecture slides)</li>
<li>Does the sample size increase or decrease as (assume that all the other parameters remain fixed):</li>
</ol>
<ul>
<li><span class="math inline">\(\sigma\)</span> decreases;</li>
<li><span class="math inline">\(\alpha\)</span> decreases;</li>
<li><span class="math inline">\(\theta\)</span> decreases.</li>
</ul>
<ol start="2" style="list-style-type: decimal">
<li>A statistician is designing a phase III clinical trial comparing a continuous outcome in two groups (experimental versus standard therapy) with a total sample size of 168 patients. The team requires that the study have at least 80% power at the 5% significance level to detect a difference of 1 (the standard deviation of the outcome is 2). The design team would like to investigate if it’s possible to have four times as many patients in the experimental group versus the control group with out having to increase the sample size.</li>
</ol>
<p>The statistician conducted the following analysis. What is the power if there are four times as many patients in the experimental group? What should the statistician recommend to the team in order for the study to have at least 80% power? For example, should the type I error rate be increased?</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" title="1"><span class="co"># sample size for two-sample z test unequal allocation</span></a>
<a class="sourceLine" id="cb184-2" title="2"><span class="co"># r is the ratio of patients in the experimental arm to control arm</span></a>
<a class="sourceLine" id="cb184-3" title="3"><span class="co"># e.g. r = 2 means that for every 2 patients in the experimental arm</span></a>
<a class="sourceLine" id="cb184-4" title="4"><span class="co"># 1 pateint is in the control arm</span></a>
<a class="sourceLine" id="cb184-5" title="5"></a>
<a class="sourceLine" id="cb184-6" title="6">size2z.uneq.test &lt;-<span class="st"> </span><span class="cf">function</span>(theta,alpha,beta,sigma,r)</a>
<a class="sourceLine" id="cb184-7" title="7">{</a>
<a class="sourceLine" id="cb184-8" title="8">  zalpha &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb184-9" title="9">  zbeta &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>beta)</a>
<a class="sourceLine" id="cb184-10" title="10">  (<span class="dv">1</span><span class="op">+</span><span class="dv">1</span><span class="op">/</span>r)<span class="op">*</span>(sigma<span class="op">*</span>(zalpha<span class="op">+</span>zbeta)<span class="op">/</span>theta)<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb184-11" title="11">}</a>
<a class="sourceLine" id="cb184-12" title="12"></a>
<a class="sourceLine" id="cb184-13" title="13"><span class="co"># power of z test as a function of allocation ratio r,</span></a>
<a class="sourceLine" id="cb184-14" title="14"><span class="co"># total sample size n, alpha, theta, and sigma</span></a>
<a class="sourceLine" id="cb184-15" title="15">pow.z.test &lt;-<span class="st"> </span><span class="cf">function</span>(r,n,alpha,theta,sigma)</a>
<a class="sourceLine" id="cb184-16" title="16">{</a>
<a class="sourceLine" id="cb184-17" title="17">  n2 &lt;-<span class="st"> </span>n<span class="op">/</span>(r<span class="op">+</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb184-18" title="18">  x &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>)<span class="op">-</span><span class="kw">abs</span>(theta)<span class="op">/</span>(sigma<span class="op">*</span><span class="kw">sqrt</span>(<span class="dv">1</span><span class="op">/</span>(r<span class="op">*</span>n2)<span class="op">+</span><span class="dv">1</span><span class="op">/</span>n2))</a>
<a class="sourceLine" id="cb184-19" title="19">  pow &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(x)</a>
<a class="sourceLine" id="cb184-20" title="20">  <span class="kw">return</span>(pow)</a>
<a class="sourceLine" id="cb184-21" title="21">}</a>
<a class="sourceLine" id="cb184-22" title="22"></a>
<a class="sourceLine" id="cb184-23" title="23"><span class="kw">plot</span>(<span class="dt">x =</span> <span class="kw">seq</span>(.<span class="dv">1</span>,<span class="dv">5</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dt">y =</span> <span class="kw">pow.z.test</span>(<span class="kw">seq</span>(.<span class="dv">1</span>,<span class="dv">5</span>,<span class="dt">by =</span> <span class="fl">0.1</span>),<span class="dv">168</span>,.<span class="dv">05</span>,<span class="dv">1</span>,<span class="dv">2</span>),<span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,</a>
<a class="sourceLine" id="cb184-24" title="24">     <span class="dt">xlab =</span> <span class="st">&quot;Allocation ratio&quot;</span>,<span class="dt">ylab =</span> <span class="st">&quot;Power&quot;</span>,</a>
<a class="sourceLine" id="cb184-25" title="25">     <span class="dt">main =</span> <span class="st">&quot;Power vs. allocation ratio with total sample size fixed at </span><span class="ch">\n</span><span class="st"> n = 168 alpha = 0.05&quot;</span>) </a></code></pre></div>
<p><img src="04-powersampsize_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<ol start="3" style="list-style-type: decimal">
<li>Let <span class="math inline">\(X_1, X_2, ..., X_n\)</span> be iid <span class="math inline">\(N\left(\mu,\sigma^2\right)\)</span>.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Show that the power function of the test <span class="math inline">\(H_0:\mu = 0\)</span> versus <span class="math inline">\(H_1:\mu &gt; 0\)</span> at <span class="math inline">\(\mu=1\)</span> is <span class="math display">\[1-\Phi\left(z_{\frac{\alpha}{2}}-\frac{\sqrt{n}}{\sigma}\right)\]</span>, where <span class="math inline">\(z_{\frac{\alpha}{2}},\)</span> is the <span class="math inline">\(100\left(1-\frac{\alpha}{2}\right)^{th}\)</span> percentile of the <span class="math inline">\(N\left(0,1\right)\)</span>.</p></li>
<li><p>Use R to calculate the power when <span class="math inline">\(n = 10\)</span>, <span class="math inline">\(\alpha = 0.01\)</span>, and <span class="math inline">\(\sigma = 1\)</span>.</p></li>
</ol>
</div>
<div id="solutions-to-questions-2" class="section level2">
<h2><span class="header-section-number">5.12</span> Solutions to Questions</h2>
<ol style="list-style-type: decimal">
<li><ol style="list-style-type: lower-alpha">
<li>One sample is iid <span class="math inline">\(N\left(\mu_1,\sigma^2\right)\)</span> and one sample is iid <span class="math inline">\(N\left(\mu_2,\sigma^2\right)\)</span>.</li>
</ol></li>
</ol>
<ol start="2" style="list-style-type: lower-alpha">
<li>Does the sample size increase or decrease as (assume that all the other parameters remain fixed):</li>
</ol>
<ul>
<li><span class="math inline">\(\sigma\)</span> decreases;</li>
</ul>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" title="1"><span class="co"># sample size for two-sample Z test equal allocation</span></a>
<a class="sourceLine" id="cb185-2" title="2">size2z.test &lt;-<span class="st"> </span><span class="cf">function</span>(theta,alpha,beta,sigma)</a>
<a class="sourceLine" id="cb185-3" title="3">{</a>
<a class="sourceLine" id="cb185-4" title="4">  zalpha &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb185-5" title="5">  zbeta &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>beta)</a>
<a class="sourceLine" id="cb185-6" title="6">  (<span class="dv">2</span><span class="op">*</span>sigma<span class="op">*</span>(zalpha<span class="op">+</span>zbeta)<span class="op">/</span>theta)<span class="op">^</span><span class="dv">2</span></a>
<a class="sourceLine" id="cb185-7" title="7">}</a>
<a class="sourceLine" id="cb185-8" title="8"></a>
<a class="sourceLine" id="cb185-9" title="9"><span class="co">#sigma=1</span></a>
<a class="sourceLine" id="cb185-10" title="10"><span class="kw">size2z.test</span>(<span class="dv">1</span>,<span class="fl">0.05</span>,.<span class="dv">1</span>,<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 42.02969</code></pre>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" title="1"><span class="co">#sigma=2</span></a>
<a class="sourceLine" id="cb187-2" title="2"><span class="kw">size2z.test</span>(<span class="dv">1</span>,<span class="fl">0.05</span>,.<span class="dv">1</span>,<span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 168.1188</code></pre>
<blockquote>
<p><span class="math inline">\(n\)</span> decreases as <span class="math inline">\(\sigma\)</span> decreases.</p>
</blockquote>
<ul>
<li><span class="math inline">\(\alpha\)</span> decreases;</li>
</ul>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" title="1"><span class="co">#alpha=0.05</span></a>
<a class="sourceLine" id="cb189-2" title="2"><span class="kw">size2z.test</span>(<span class="dv">1</span>,<span class="fl">0.05</span>,.<span class="dv">1</span>,<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 42.02969</code></pre>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb191-1" title="1"><span class="co">#alpha=0.01</span></a>
<a class="sourceLine" id="cb191-2" title="2"><span class="kw">size2z.test</span>(<span class="dv">1</span>,<span class="fl">0.01</span>,.<span class="dv">1</span>,<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 59.51755</code></pre>
<blockquote>
<p><span class="math inline">\(n\)</span> increases as <span class="math inline">\(\alpha\)</span> decreases.</p>
</blockquote>
<ul>
<li><span class="math inline">\(\theta\)</span> decreases.</li>
</ul>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb193-1" title="1"><span class="co">#theta=1</span></a>
<a class="sourceLine" id="cb193-2" title="2"><span class="kw">size2z.test</span>(<span class="dv">1</span>,<span class="fl">0.05</span>,.<span class="dv">1</span>,<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 42.02969</code></pre>
<div class="sourceCode" id="cb195"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb195-1" title="1"><span class="co">#theta=2</span></a>
<a class="sourceLine" id="cb195-2" title="2"><span class="kw">size2z.test</span>(<span class="dv">2</span>,<span class="fl">0.05</span>,.<span class="dv">1</span>,<span class="dv">1</span>)</a></code></pre></div>
<pre><code>## [1] 10.50742</code></pre>
<blockquote>
<p><span class="math inline">\(n\)</span> increases as <span class="math inline">\(\theta\)</span> decreases.</p>
</blockquote>
<ol start="2" style="list-style-type: decimal">
<li><blockquote>
<p>If r=4 then the power is</p>
</blockquote></li>
</ol>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb197-1" title="1">pow.z.test &lt;-<span class="st"> </span><span class="cf">function</span>(r,n,alpha,theta,sigma)</a>
<a class="sourceLine" id="cb197-2" title="2">{</a>
<a class="sourceLine" id="cb197-3" title="3">  n2 &lt;-<span class="st"> </span>n<span class="op">/</span>(r<span class="op">+</span><span class="dv">1</span>)</a>
<a class="sourceLine" id="cb197-4" title="4">  x &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="op">-</span>alpha<span class="op">/</span><span class="dv">2</span>)<span class="op">-</span><span class="kw">abs</span>(theta)<span class="op">/</span>(sigma<span class="op">*</span><span class="kw">sqrt</span>(<span class="dv">1</span><span class="op">/</span>(r<span class="op">*</span>n2)<span class="op">+</span><span class="dv">1</span><span class="op">/</span>n2))</a>
<a class="sourceLine" id="cb197-5" title="5">  pow &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(x)</a>
<a class="sourceLine" id="cb197-6" title="6">  <span class="kw">return</span>(pow)</a>
<a class="sourceLine" id="cb197-7" title="7">}</a>
<a class="sourceLine" id="cb197-8" title="8"></a>
<a class="sourceLine" id="cb197-9" title="9"><span class="kw">pow.z.test</span>(<span class="dv">4</span>,<span class="dv">168</span>,<span class="fl">0.05</span>,<span class="dv">1</span>,<span class="dv">2</span>)</a></code></pre></div>
<pre><code>## [1] 0.7364151</code></pre>
<blockquote>
<p>The statistician can either increase <span class="math inline">\(n\)</span>, <span class="math inline">\(\alpha\)</span>, or <span class="math inline">\(\theta\)</span>, or decrease <span class="math inline">\(\sigma\)</span>. The statistician &gt;should recommend increasing <span class="math inline">\(n\)</span>. Most regulatory agencies have fixed <span class="math inline">\(\alpha=0.05\)</span>. <span class="math inline">\(\theta=1\)</span> is the smallest meangingful clinical difference so it wouldn’t be rationale to increase <span class="math inline">\(\theta\)</span> since the study might miss detecting a clinically significant difference if <span class="math inline">\(\theta\)</span> is increased. Decreasing <span class="math inline">\(\sigma\)</span> is usually not possible since the variation of the outcome measure is difficult to change in practice.</p>
</blockquote>
<ol start="3" style="list-style-type: decimal">
<li></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>The test rejects when</li>
</ol>
<p><span class="math display">\[\frac{\bar X}{\sigma/\sqrt{n}} \ge z_{\alpha/2}.\]</span> The probability the test rejects when <span class="math inline">\(\mu=1\)</span> is:</p>
<p><span class="math display">\[\begin{aligned}
P\left(\frac{\bar X}{\sigma/\sqrt{n}} \ge z_{\alpha/2}\right) 
&amp;= P\left({\bar X} \ge z_{\alpha/2} \cdot \sigma/\sqrt{n} \right) \\
&amp;= P\left(\frac{\bar X - 1}{\sigma/\sqrt{n}} \ge \frac{z_{\alpha/2} \cdot \sigma/\sqrt{n}-1}{\sigma/\sqrt{n}} \right) \\
&amp;= P\left(Z \ge \frac{z_{\alpha/2} \cdot \sigma/\sqrt{n}-1}{\sigma/\sqrt{n}} \right) \\
&amp;= 1-\Phi\left(\frac{z_{\alpha/2} \cdot \sigma/\sqrt{n}-1}{\sigma/\sqrt{n}} \right) \\
&amp;= 1-\Phi\left(z_{\alpha/2} - \frac{\sqrt{n}}{\sigma} \right) \\
\end{aligned}\]</span></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Use R to calculate the power when <span class="math inline">\(n=10\)</span>, <span class="math inline">\(\alpha=0.01\)</span>, and <span class="math inline">\(\sigma=1\)</span>.</li>
</ol>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" title="1">zalpha2 &lt;-<span class="st"> </span><span class="kw">qnorm</span>(<span class="dv">1</span><span class="fl">-0.01</span><span class="op">/</span><span class="dv">2</span>)</a>
<a class="sourceLine" id="cb199-2" title="2"><span class="dv">1</span><span class="op">-</span><span class="kw">pnorm</span>(zalpha2<span class="op">-</span><span class="kw">sqrt</span>(<span class="dv">10</span>))</a></code></pre></div>
<pre><code>## [1] 0.7212129</code></pre>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-cohen1992power">
<p>Cohen, Jacob. 1992. “A Power Primer.” <em>Psychological Bulletin</em> 112 (1): 155.</p>
</div>
<div id="ref-yin2013clinical">
<p>Yin, Guosheng. 2013. <em>Clinical Trial Design: Bayesian and Frequentist Adaptive Methods</em>. Vol. 876. John Wiley; Sons.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="completely-randomized-designs-comparing-two-treatments.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="causal-inference.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
